### ISSUE TITLE
question about equation (3)

### ISSUE THREAD

**Issue by emergencyd** [ialhashim/DenseDepth#1]
Hi~
Is the parenthesis missed? 
What is this equation for? calculating difference or penalizing distortions? then how?
Thanks! 

![image](https://user-images.githubusercontent.com/16423998/50589839-2ee9da00-0ec3-11e9-9145-40fd3b9129e4.png)

**Comment by ialhashim** [comment]
Yes, there should be a parenthesis around the gradients for x and y. You can see the relevant code [here](https://github.com/ialhashim/DenseDepth/blob/f0ade6698bc98a48d605e011ef34bef43ae5abc0/loss.py#L12).
