### ISSUE TITLE
HI! I try to run this demo to look the result but there seem to be some questions.

### ISSUE THREAD

**Issue by xjtucx** [ialhashim/DenseDepth#10]
When I run test.py,It has this error,I have consulted for a long time and still don't know how to solve it,Can you help me for this?Thank you very much.  : ) 
 File "/home/hpc/cx/DenseDepth-master/test.py", line 38, in <module>
    viz = display_images(outputs.copy(), inputs.copy())
  File "/home/hpc/cx/DenseDepth-master/utils.py", line 80, in display_images
    return skimage.util.montage(all_images, multichannel=True, fill=(0,0,0))
AttributeError: module 'skimage.util' has no attribute 'montage'

**Comment by ialhashim** [comment]
Check the version of `skimage`, I think you will find this function in `skimage==0.14.0` or above.
