### ISSUE TITLE
FPS of model

### ISSUE THREAD

**Issue by kHarshit** [ialhashim/DenseDepth#100]
I want to find the time per image during inference. Since the code is written to pass all the inputs at once to the model, it seems not to be possible. Thus, I try to find the total time taken by `model.predict` method and divide it by number of images to get rough idea of FPS.
 
https://github.com/ialhashim/DenseDepth/blob/ed044069eb99fa06dd4af415d862b3b5cbfab283/test.py#L33-L34

```
start = timeit.default_timer()
outputs = predict(model, inputs)
stop = timeit.default_timer()
print('time: ', stop-start)
# then time/number _of_images
```

But, usually, the first image takes a lot of time compared to subsequent images during inference (thus it will not give a correct estimate). Is there a way that I can discard the time taken by the first image?

**Comment by ialhashim** [comment]
Simply call it twice, the first time is just a warm up. It shouldn't be too slow but also it might not be real-time.
