### ISSUE TITLE
About the "callback" for depth training data.

### ISSUE THREAD

**Issue by shuluoshu** [ialhashim/DenseDepth#101]
Hi, @ialhashim , I have some confusion about the pipeline. 

1. In gt data preparation in **data.py**,   `batch_y = DepthNorm(y_real, maxDepth=self.maxDepth)`, here the y_real is converted into `maxD/ y_real`. 
2. In **callbacks.py**  Line 49, `x_train, y_train = x_train[0], np.clip(DepthNorm(y_train[0], maxDepth=1000), minDepth, maxDepth) / maxDepth ` ， so the actual 
`y_train = maxD / batch_y / maxD = 1/ batch_y = y_real/  maxD`
This is confusing.  Do I miss anything? I'm not familiar with Keras,  I don't know the reason for using the transform in **callbacks.py**
Looking forward for your reply. Thanks.

**Comment by ialhashim** [comment]
You can ignore the DepthNorm and dividing the maximum depth if you want a clearer formulation. The advantages are small.
