### ISSUE TITLE
Error: AttributeError: module 'tensorflow._api.v2.image' 

### ISSUE THREAD

**Issue by Syirrus** [ialhashim/DenseDepth#102]
I get the following error when I attempt to run the test.py script.
AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_images'

I'm running Ubuntu 19.10 Tensorflow 2.1. All python packages have been installed. I'm also running Python 3.7.

**Comment by Leon1995-ai** [comment]
> 尝试运行test.py脚本时出现以下错误。
> AttributeError：模块“ tensorflow._api.v2.image”没有属性“ resize_images”
> 
> 我正在运行Ubuntu 19.10 Tensorflow 2.1。所有python软件包都已安装。我也在运行Python 3.7。
Maybe your tensorflow version is too high

**Comment by Leon1995-ai** [comment]
Maybe your tensorflow version is too high.

**Comment by nosy-b** [comment]
I had the same error cause of newer Tensorflow version yes. 

The resize function has been renamed so the solution is:
Change it in 'layers.py', _resize_images_ becomes _resize_ (and remove the last parameter)

**Comment by aferriss** [comment]
I had the same issue. If you want to keep the align corners option on you can do 
```python
tf.compat.v1.image.resize(inputs, [height, width], method=tf.image.ResizeMethod.BILINEAR, align_corners=True)
```
