### ISSUE TITLE
Mistake in PyTorch/data.py?

### ISSUE THREAD

**Issue by LiZhenLiangLee** [ialhashim/DenseDepth#103]
line 150 in PyTorch/data.py
` transformed_testing = depthDatasetMemory(data, nyu2_train, transform=getNoTransform())`
I think it should be nyu2_test instead of nyu2_train.

but in function `loadZipToMem()`, there is only nyu2_train 
`nyu2_train = list((row.split(',') for row in (data['data/nyu2_train.csv']).decode("utf-8").split('\n') if len(row) > 0))`
there is  no nyu2_test which contains the filename in **nyu2_test.csv**

So, is this a mistake?  And how can I fix it? Add nyu2_test in function `loadZipToMem()` and modify line 150 ?

**Comment by ialhashim** [comment]
PyTorch code is just an experiment. I didn't include the training set loading. It should be easy to add.
