### ISSUE TITLE
training on more gpus results in longer time for the step!

### ISSUE THREAD

**Issue by bat3a** [ialhashim/DenseDepth#104]
hi
i am training nyu dataset and used the tags (--gpus 1 --bs 6) on aws v100 gpu with these results:
**450ms/step 3803s/epoch**
i then used the tags (--gpus 4 --bs 24) on an aws machine with aws x4 v100 and got:
**2s/step  3471s/epoch**

this is strange as the time should be ~ 1/4 the single gpu machine, also tried with x8 v100 and time got even longer!

i used ubuntu 18.04 and 16.04 with tensorflow gpu 1.13.2, keras 2.2.4.

**Comment by ialhashim** [comment]
I think this is a Keras issue.
