### ISSUE TITLE
Is it possible to have closer objects brighter and farther objects darker?

### ISSUE THREAD

**Issue by sarimmehdi** [ialhashim/DenseDepth#106]
Hello. I use your code to get grayscale images which I then use as input to Pseudo Lidar to get point cloud. Pseudo Lidar requires closer points to brighter and farther points to be darker. The output of your network is the opposite. Is there any way to reverse this?

**Comment by ialhashim** [comment]
The function "predict" in utils.py outputs the depth from 0 to 1. You can then do 1-predict which should give you the range you want. It's a simple transformation.

**Comment by sarimmehdi** [comment]
I decided to make this change in display_images function in utils.py:
        ```
if is_colormap:
            rescaled = outputs[i][:,:,0]
            if is_rescale:
                rescaled = rescaled - np.max(rescaled)
                rescaled = rescaled / np.min(rescaled)
            imgs.append(plasma(rescaled)[:,:,:3])
        else:
            imgs.append(to_multichannel(outputs[i]))
```
