### ISSUE TITLE
Video Stream

### ISSUE THREAD

**Issue by OmarLaz97** [ialhashim/DenseDepth#107]
Thank you for your amazing work !
Can i run the model on a smartphone using a video stream and get a real time performance ?

**Comment by ialhashim** [comment]
There is a quality vs. speed tradeoff. Our model is heavy for a phone. You can look at a faster less accurate solution here

https://github.com/dwofk/fast-depth

**Comment by OmarLaz97** [comment]
Will it help if i changed the DenseNet model encoder with a lighter weight model ?

**Comment by ialhashim** [comment]
Maybe, you should try and see.

**Comment by ochen1** [comment]
You can also try pydnet, it is quick and light (0.3s/frame on an i7)

The result is horrible for my purposes tho :frowning: 

https://github.com/mattpoggi/pydnet
