### ISSUE TITLE
DenseDepth.ipynb doesn't work on external images

### ISSUE THREAD

**Issue by yasserius-ml** [ialhashim/DenseDepth#108]
I tried using some random PNG images and predicting the depth, but getting weird errors due to  dimensions mismatch of tensors within the network, like this:

```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [2,1664,40,62] vs. shape[1] = [2,256,41,62]
	 [[{{node up1_concat_3/concat}}]]
	 [[conv3_3/BiasAdd/_26149]]
  (1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [2,1664,40,62] vs. shape[1] = [2,256,41,62]
	 [[{{node up1_concat_3/concat}}]]
```

I edited the code to remove the A-channel from PNG images, please upload your own PNG image to colab and leave it in the root directory of colab, then run all cells

**colab link:** https://colab.research.google.com/drive/1Su_eXirOWTLjQ80ezzpCE3rLc6N_PzxV

I know reading through the mammoth amount of code is a huge task, but any sort of help will be appreciated, and the improved code will be put online for everyone to use.

Thanks in advance! :D

**Comment by ialhashim** [comment]
I am not sure if its related, but for now try to first [resize](https://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.resize) images to (width 640, height 480) when using `nyu` trained model. It should be working.

**Comment by yasserius-ml** [comment]
It worked, thanks so much! :D

colab link: https://colab.research.google.com/drive/1Su_eXirOWTLjQ80ezzpCE3rLc6N_PzxV

would you like me to create an interactive colab with "upload image" and send you a pull request?

**Comment by ialhashim** [comment]
Sure! Just make it as simple as you can.
