### ISSUE TITLE
train other data

### ISSUE THREAD

**Issue by boni-hu** [ialhashim/DenseDepth#11]
Hello,
I want to train my own data.
`if args.data == 'nyu':
    train_generator, test_generator = get_nyu_train_test_data( args.bs )
`
How to modify the code?

Sincerely,
HuBoni

**Comment by ialhashim** [comment]
You would need to modify `data.py`. I'll explain the following functions:
- `get_nyu_train_test_data` returns two generators (kind of like an array) such that `train_generator[i]` returns `x, y` representing the RGB input and the ground truth depth maps of shapes `(batch size  x  height  x  width  x  3)` and `(batch size  x  height  x  width  x  1)` respectively.
- You can build on the `NYU_BasicAugmentRGBSequence` class for your own data. The main thing is to have a function `__getitem__` that generates a batch of `x,y` for input RGB and depth.
- Make sure you are correctly specifying the range of depth and that RGB is in [0,1]. Different parts of the code might assume that the maximum depth is 1000 and minimum is 10, so adjust accordingly.
- Always make sure that the images in each batch is random / shuffled before hand.

**Comment by boni-hu** [comment]
OK, thank you very much, i will try it!

**Comment by boni-hu** [comment]
Hello, 
when i run ' python train.py --data nyu --gpus 1 --bs 1 '
this problem arise "KeyError: './dataset/lab/train_lab/train_data/train_data_rgb/DJI_0057.jpg'
"
when i run `python train.py --data nyu --gpus 1 --bs 8`
this problem arise KeyError: './dataset/lab/train_lab/train_data/train_data_rgb/DJI_0019.jpg'
Do you know the reason?

Sincerely,
HuBoni

**Comment by ialhashim** [comment]
I think you need to modify the code some more to adapt it to your dataset. I recommend you don't start training right away. First you check if your data loader is working correctly step by step. You can even test it in a jupyter notebook and look at tensor shapes and examine the RGB and depth maps. Once you are certain that the generator is outputting (batch size x height x width x 1) then you continue to training.

**Comment by boni-hu** [comment]
Thank you very much!
 I already train my data. And i faced a new problem, when i train my data, the loss==nan.I speculate that this may be related to the depth value of the data set. I want to know what minDepth and maxDepth represent in your code. The paper mentions that the maximum depth of the NYU data set is 10 meters.

**Comment by ialhashim** [comment]
Make sure to clip your depth values from `minDepth` to `maxDepth`. For NYU it is in centimeters from 10cm to 1000cm.

**Comment by boni-hu** [comment]
Thank you very much! You are very friendly. ^_^

**Comment by bradasteiner** [comment]
Hi, I am also getting loss == nan. Were you able to resolve this issue?

**Comment by bradasteiner** [comment]
Figured out the issue. The depth masks need to be 16 bit pngs and the images 8 bit

**Comment by ialhashim** [comment]
You could also modify the data range and processing in the network. No real reason to stick with the current ranges.

**Comment by bradasteiner** [comment]
Do you know if the trained kitti model expects 16 bit depth masks and 8 bit images as well?

**Comment by ialhashim** [comment]
The trained model only expects images in the range `[0,1]`. The output in meters can be converted to a `[0,80]` range by computing  `80/model.predict(x)`. If you want to continue the training with the same trained model you only need to supply batches of RGB in the range `[0,1]` and depth maps in the range `1.0 / depth in [1.0,80]`.

**Comment by prithvi-poddar** [comment]
I am generating my own data set to train it upon, using a 3-d lidar to get the ground truth. The rage of this lidar is 100m. So do I set `maxDepth` as 100000?

**Comment by ialhashim** [comment]
Its really up to you to decide what range you would like the training to happen at. You can use any linear scaling of the values and i believe the results should be the same. Just make sure when you view the data or compute the depths you are using the correct range.

**Comment by sadique-adnan** [comment]
> with

The range of depth maps should be max_depth / depth in [1.0,80.0] similar to what DepthNorm does for NYU dataset, where max_depth for KITTI should be 80.0?

**Comment by sadique-adnan** [comment]
> The trained model only expects images in the range `[0,1]`. The output in meters can be converted to a `[0,80]` range by computing `80/model.predict(x)`. If you want to continue the training with the same trained model you only need to supply batches of RGB in the range `[0,1]` and depth maps in the range `1.0 / depth in [1.0,80]`.

The range of depth maps should be max_depth / depth in [1.0,80.0] similar to what DepthNorm does for NYU dataset, where max_depth for KITTI should be 80.0?
