### ISSUE TITLE
Custom data KeyError : 

### ISSUE THREAD

**Issue by kimtaehyeong** [ialhashim/DenseDepth#113]
Hi.
Thanks for the good code.
I am trying to learn custom data,
I entered the following command to learn according to the format provided (.zip-> read excel).
python train.py --data custom --gpus 1 --bs2
However, the following error occurred.
"""
  x = np.clip(np.asarray(Image.open( BytesIO(self.data[sample[0]]) )).reshape(480,640,3)/255,0,1)
KeyError: 'endoscopy/custom_train/10607_rgb.png' 
"""

How do I solve it?
The size of my dataset is train: 13928 / test: 2087, and the data size is set equal to 640x480.
Thank you.

**Comment by kimtaehyeong** [comment]
The error occurred because the data path created by .csv was incorrect.
I Solved it.

**Comment by xiaoyaozi2005** [comment]
> The error occurred because the data path created by .csv was incorrect.
> I Solved it.

Hi, I met the same error, but I have confirmed that my path was correct.
Would you please introduce how you solved the problem in detail?

Than you

**Comment by LiAnwen99** [comment]
> > The error occurred because the data path created by .csv was incorrect.
> > I Solved it.
> 
> Hi, I met the same error, but I have confirmed that my path was correct. Would you please introduce how you solved the problem in detail?
> 
> Than you

Hi, have you solved the problem?

**Comment by kimtaehyeong** [comment]
It's been a long time so I can't remember exactly
I remember that it was not good if there was a pixel value of 0.
