### ISSUE TITLE
question about mindepth

### ISSUE THREAD

**Issue by kimtaehyeong** [ialhashim/DenseDepth#115]
Hi.
My question is about mindepth.
In case of nyu data, it is [10 ~ 1000]cm, but in case of my data set, it is [0 ~ 20]cm. If so, how do you specify mindepth?
maxdepth is learning by changing to 20.
Thank you.

**Comment by ialhashim** [comment]
I think there are three ways. You can set it to some very small number like `0.001`. Or you can altogether replace the function `DepthNorm` with:
```
def DepthNorm(x, maxDepth): return x
``` 
Finally, you could just scale your input linearly to be in the range from 10 to 1000.

**Comment by kimtaehyeong** [comment]
Thank you so much!!
