### ISSUE TITLE
How do I test on KITTI ?

### ISSUE THREAD

**Issue by ChuangbinC** [ialhashim/DenseDepth#12]
Hi, I want to know how do I test on KITTI? I download the kitti model and I change the test code but it has a bug.

**Comment by ialhashim** [comment]
What sort of bug / error message are you getting?

**Comment by ChuangbinC** [comment]
@ialhashim I run the code ` CUDA_VISIBLE_DEVICES=1 python test.py` and I get this error. The input image is a `(375, 1242, 3)` picture in kitti and the pre-trained model is the kitti model that you provide.
![image](https://user-images.githubusercontent.com/18183832/54939569-dd059d00-4f63-11e9-842a-4380c500aff9.png)

**Comment by ialhashim** [comment]
Can you try resizing your input to (384, 1248, 3) and see if that works? the error seems related to the expected input dimension.

**Comment by ChuangbinC** [comment]
@ialhashim Thanks! It works! I want to know why it needs resize to (384, 1248, 3)?

**Comment by ialhashim** [comment]
The KITTI dataset unfortunately has several different dimensions, so the first thing to do was make sure we use a reasonable image size that is close to an "average". Second, the encoder we used here is DenseNet which was designed with images of dimensions that are multiples of 32px (especially if you want to use a decoder). The error you were seeing was at the skip connection point where the spatial shape of the tensor was off by 1x1px. If you use images that are multiples of 32px it should always work.
