### ISSUE TITLE
NYU test images look strange

### ISSUE THREAD

**Issue by DavidSriker** [ialhashim/DenseDepth#122]
I created a `bash` script that download the nyu data from the drive you provided, but looking at the test gt the depth maps looks distorted.

Sample of the images from the nyu_data.zip

![00000_colors](https://user-images.githubusercontent.com/32892394/80965013-8337fd80-8e1a-11ea-9936-375f14172822.png)
![00000_depth](https://user-images.githubusercontent.com/32892394/80965021-87641b00-8e1a-11ea-936c-6bf8a2dca981.png)
 

Other example

![00017_colors](https://user-images.githubusercontent.com/32892394/80965055-9a76eb00-8e1a-11ea-9f2c-e814d3576531.png)
![00017_depth](https://user-images.githubusercontent.com/32892394/80965060-9d71db80-8e1a-11ea-852c-0cf0f190dbb8.png)

Is there some preprocessing that is necessary here?

Thanks

**Comment by ialhashim** [comment]
Its just too dark. Try scaling the image to what you need.

**Comment by DavidSriker** [comment]
> Its just too dark. Try scaling the image to what you need.

I disagree, the first depth image is all black, the value is 1000 throughout the image.

Is there might be a problem in the data you provided?

**Comment by aiarjun** [comment]
I have the same question. In the Pytorch script, for loading the test data, you have divided it by 1000, while the train data is multiplied by 1000. Why is that?

**Comment by ialhashim** [comment]
@aiarjun the were saved at different formats. I was using data prepared by a previous paper. I don't know why they originally did that but I tried to use the same data to help compare the results.

**Comment by aiarjun** [comment]
Thank you for the answer, @ialhashim . Great work! I have one more question, and it would be really helpful if you could answer it.

In the nyu_test.zip depth data, I am unable to find the scale of the data. Could you just give me the formula for converting the range of the image to 1000? i.e. something like depth = depth/1000? I have tried everything, and I am unable to get the answer.

Thank you.
