### ISSUE TITLE
Loading pre-trained model with tensorflow 2 BilinearUpSampling2D layer

### ISSUE THREAD

**Issue by cirvladimir** [ialhashim/DenseDepth#123]
I'm trying to use the pre-trained model with tensorflow 2. Looking at test.py the model requires a custom BilinearUpSampling2D layer which uses keras instead of tensorflow.keras. Is there by any chance working tensorflow 2 code somewhere or a tensorflow 2 compatible implementation of the upsampling layer?

**Comment by ialhashim** [comment]
I am not supporting the tensorflow 2 version right now. I think it should be easy to interchange it. I'd be happy to take a pull request if you manage to get it working.
