### ISSUE TITLE
Convert to Tflite

### ISSUE THREAD

**Issue by anasgit** [ialhashim/DenseDepth#124]
How can we convert a pretrained model to Tflite?
Many thanks in advance.

**Comment by ialhashim** [comment]
I am not familiar with Tflite. I am sorry I can't help with that. One thing to keep in mind, the best model we have tested is heavy for small machines.

**Comment by iram01** [comment]
@anasgit can u plz help me if you have worked on Tflite model. Actually I converted the pretrained model to Tflite but not able to use as it gives shape mismatch error.
