### ISSUE TITLE
Requirements Qt viewer

### ISSUE THREAD

**Issue by JunkyByte** [ialhashim/DenseDepth#125]
Hello, thanks for the great code source and paper, the code installs fine and seems very easy to apply to different datasets.
I did not manage to make the viewer run though, I can’t attach tracebacks right now but I will in a later moment if you care; could you share the version of the dependencies (and the operating system) you use and know that work for the Qt viewer?

Thank you very much.

**Comment by ialhashim** [comment]
Please look at other closed issues in the repo, you will find all the details on the Qt demo.

**Comment by JunkyByte** [comment]
Thanks, must be blind these days
