### ISSUE TITLE
How to check if fill_depth_colorization result is good for KITTI?

### ISSUE THREAD

**Issue by TimbusCalin** [ialhashim/DenseDepth#127]
I have this code below:
    image_rgb = np.array(Image.open('C:\\Users\\Calin\\Desktop\\test_inpaint\\0000000005_rgb.png'))
    image_depth = np.array(Image.open('C:\\Users\\Calin\\Desktop\\test_inpaint\\0000000005.png'))
    image_depth_filled = fill_depth_colorization(imgRgb=image_rgb,imgDepthInput=image_depth,alpha=1)

![Figure_1](https://user-images.githubusercontent.com/23454613/82903759-1a9bf680-9f6a-11ea-97be-300a2b8027b4.png)

In the picture above, I realized that, during the conversion process, the closest pixels in the KITTI dataset may have something like 6 meters.... Is this a correct result? 

Thank you for your help. @ialhashim

**Comment by ialhashim** [comment]
I don't remember what is the standard or usual minimum distance for KITTI. You can explore that statistics by looking the data before filling.

**Comment by TimbusCalin** [comment]
Thank you for your time and answer @ialhashim
