### ISSUE TITLE
Pretrained models differs from code architecture

### ISSUE THREAD

**Issue by MoltenMuffins** [ialhashim/DenseDepth#130]
I was trying to load the trained weights into the Tensorflow 2 implementation of the DenseDepth model, however I found that prediction outputs of the original model vs the TF2 model were different.

Upon closer inspection of the model.summary() for both the KITTI and the NYU_V2 pretrained models, it seems that a different variation of the model upsampling layer has been used than shown in [master/model.py](https://github.com/ialhashim/DenseDepth/blob/master/model.py) or  [master/Tensorflow/model.py](https://github.com/ialhashim/DenseDepth/blob/master/Tensorflow/model.py). In particular it seems that only one Leaky Relu layer is used at the end of the upsampling layer for the pretrained kitti, rather than two.

In addition to that, I had to change
`decode_filters = int(encoder._encoder.layers[-1].output[0].shape[-1] // 2)` to `decode_filters = int(encoder._encoder.layers[-1].output[0].shape[-1])` in order to ensure the ported model output shape was correct.

Here is the `model.summary()` of the pretrained kitti model.  Here I have just included the layers from the first two upsampling layers as the full printout would be too long.

```
up1_upsampling2d (BilinearUpSam (None, None, None, 1 0           conv2[0][0]                      
__________________________________________________________________________________________________
up1_concat (Concatenate)        (None, None, None, 1 0           up1_upsampling2d[0][0]           
                                                                 pool3_pool[0][0]                 
__________________________________________________________________________________________________
up1_convA (Conv2D)              (None, None, None, 8 14377792    up1_concat[0][0]                 
__________________________________________________________________________________________________
up1_convB (Conv2D)              (None, None, None, 8 6230848     up1_convA[0][0]  <- Code indicates a LeakyRelU before this layer!
__________________________________________________________________________________________________
leaky_re_lu_1 (LeakyReLU)       (None, None, None, 8 0           up1_convB[0][0]                  
__________________________________________________________________________________________________
up2_upsampling2d (BilinearUpSam (None, None, None, 8 0           leaky_re_lu_1[0][0]              
__________________________________________________________________________________________________
up2_concat (Concatenate)        (None, None, None, 9 0           up2_upsampling2d[0][0]           
                                                                 pool2_pool[0][0]                 
__________________________________________________________________________________________________
up2_convA (Conv2D)              (None, None, None, 4 3594656     up2_concat[0][0]                 
__________________________________________________________________________________________________
up2_convB (Conv2D)              (None, None, None, 4 1557920     up2_convA[0][0] <- Code indicates a LeakyRelU before this layer!
__________________________________________________________________________________________________
leaky_re_lu_2 (LeakyReLU)       (None, None, None, 4 0           up2_convB[0][0]                  
_________________________________________________________________________________
```

I'm not sure if I did something wrong or if I misunderstood something from the code/paper so it'd be great if someone could corroborate my findings.

**Comment by ialhashim** [comment]
The model was modified [check here.](https://github.com/ialhashim/DenseDepth/commit/ea4a45594f2fa2ab1d33c6130e175a98213d382d#diff-93ff136fae812392eb0f68d1ce89b7fe)

**Comment by MoltenMuffins** [comment]
@ialhashim Thanks for your response! Is there any intention of updating the links to the pretrained models in the repo `README.md`? Otherwise it might be good to include a short note regarding the difference in layers
