### ISSUE TITLE
KITTI train subset

### ISSUE THREAD

**Issue by VProv** [ialhashim/DenseDepth#134]
Hello! 

In the article, you wrote that you use a subset of around 26K images, from the left view. But on the github page "For our training, we used the subset defined here." there is a link to .csv file with 85898 images. Could you please give a file with your 26K subset?

**Comment by ialhashim** [comment]
At this time I don't have access to the KITTI experiments since I left my postdoc institute. I believe our new paper AdaBins should have the training set soon.
