### ISSUE TITLE
Anyone run this on equirectangular images?

### ISSUE THREAD

**Issue by gateway** [ialhashim/DenseDepth#135]
Looking for a way to create depth maps from single equirectangular 360 images to then be used in virtual tours.

Thoughts?

**Comment by ialhashim** [comment]
Take a look at this project https://fuenwang.ml/project/bifuse/?fbclid=IwAR0qKLtkrkGgtGiu2zdm7YpW-3DkBPzdYvonWYUqyv1yKFA1nLYz5Q5qqEM
