### ISSUE TITLE
Test list of NYU dataset

### ISSUE THREAD

**Issue by ghost** [ialhashim/DenseDepth#136]
Hi, 

May I ask what is the test list for NYU v2? And where I can find it ? 

I am very new in this field, and I see lots of paper claims they test on 694/654 frames from 1449 NYU labeled set,  following Eigen split or official split. But I cannot the list of it. 

Could you tell me where this split exactly is ?  A link toward it would be very helpful. 

Thanks!

**Comment by yangfengt123** [comment]
My best guess is at http://horatio.cs.nyu.edu/mit/silberman/indoor_seg_sup/splits.mat
Please correct me if I am wrong.
