### ISSUE TITLE
about training 

### ISSUE THREAD

**Issue by boni-hu** [ialhashim/DenseDepth#14]
Hello,
When i train my own data , this error occurred. I check the code and data, but already don't know the reason. The error as follows:
![error](https://user-images.githubusercontent.com/37893834/55218072-fb0d1f00-523b-11e9-95f8-10cfc3efa740.png)

Sincerely,
Hu Boni

**Comment by ialhashim** [comment]
This is a known Keras issue. Look at the suggestions here https://github.com/keras-team/keras/issues/9342

To test if everything is working you can enable the data debugging like so: https://github.com/ialhashim/DenseDepth/blob/master/data.py#L27
