### ISSUE TITLE
model.save('/model.h5')

### ISSUE THREAD

**Issue by Unitshockresponse** [ialhashim/DenseDepth#141]
Hi,ialhashim.
I ran the code in the tensorflow V2 framework, but I want to save the training results as a .h5 file for easy calling in test.py. I added a line of code model.save('/model.h5') to colab, and it will report an error when running. I wonder if you have any good solutions. Thank you very much!

![QQ图片20200806213923](https://user-images.githubusercontent.com/59330921/89538596-5d613100-d82d-11ea-918d-71bda7f3d584.png)

**Comment by ialhashim** [comment]
Maybe it doesn't like the path, try 'model.h5' or './model.h5'.
