### ISSUE TITLE
Problem in understanding scaled version result

### ISSUE THREAD

**Issue by sanbuddhacharyas** [ialhashim/DenseDepth#142]
![Screenshot (14)](https://user-images.githubusercontent.com/33871656/90415917-81e0c700-e0d1-11ea-83ac-e3508a6f8b73.png)
How result is improved with applied scaling? How ground truth median data is used to improve your result? I am also doing similar type of project so, please can you help me understand this scaling effect in your result.

**Comment by ialhashim** [comment]
This is idea was discussed in prior work. It basically just means to shift the median of the prediction such that it better matches the ground truth. This is not an improvement. Its just a shows that a lot of the error comes from a global shift in the prediction that could be solved for.
