### ISSUE TITLE
TypeError: 'Not JSON Serializable

### ISSUE THREAD

**Issue by sandippaul7204** [ialhashim/DenseDepth#144]
I am interested in your depth map algorithm. When I try to train (train.py) I get the following error when the 'basemodel.save'  function runs after one epoch. 
################################
# Start training
model.fit_generator(train_generator, callbacks=callbacks, validation_data=test_generator, epochs=args.epochs, shuffle=True)
# Save the final trained model:
basemodel.save(runPath + '/model.h5') 
##################################
Error reported

TypeError: 'Not JSON Serializable
################################
You have posted on the same issue as a Keras bug. I am now stuck at this point. I would like to know the solution that you have implemented so that I can train the network. 
Thanks in advance.
Sandip Paul
PHD Student

**Comment by ialhashim** [comment]
You can find the solution in that same issue. I followed someone's idea to modify the keras code.

**Comment by sandippaul7204** [comment]
I tried. Still facing problem. I would be grateful if can help in that modified part. Thanks.
