### ISSUE TITLE
model depth units

### ISSUE THREAD

**Issue by B0RJA** [ialhashim/DenseDepth#146]
Thank you for sharing your work. I just want to share some keys about depth representation in the nyu data and in the model to check with the author. There are several closed issues on this topic but I can't get the big picture.

1. The provided depth images in the `nyu2_train` folder are 8-bit gray PNGs ranging from 0 to 256. These digital levels correspond to depths from 0 to 10m.

Train images are first loaded, scaled and clipped between o and maxDepth (1000 in the code):

https://github.com/ialhashim/DenseDepth/blob/f376b01820cad7f57222c5a24e40e89577a2c269/data.py#L70-L71

and then processed using `DepthNorm`:

https://github.com/ialhashim/DenseDepth/blob/a72e70161d6d2afb2978824ae875310696349472/utils.py#L4-L5

This function is indeed an inversion which gives more dynamic range to the closest distances and produces a range of values from 1 to 10.

```
level	m	scaled	DepthNorm
25	1.0	98	10.2
50	2.0	196	5.1
102	4.0	400	2.5
255	10.0	1000	1.0
```

2. The provided depth images in the `nyu2_test` folder are 16-bit gray PNGs. In this case, digital values typically range from 1000 to 10000 levels and correspond to Kinect's measurement range in mm.

Test images are first divided by 10 to obtain a range between 100 and 1000, that matches the train images range, and then processed using `DepthNorm` to get a final range from 1 to 10.

https://github.com/ialhashim/DenseDepth/blob/f376b01820cad7f57222c5a24e40e89577a2c269/data.py#L105-L106

3. In the prediction phase, the results of the model are processed using `DepthNorm` to revert the inversion and get depth units between 0 and 1000. Note that calling `DepthNorm` twice leaves the data intact and the function is also its inversion.

https://github.com/ialhashim/DenseDepth/blob/a72e70161d6d2afb2978824ae875310696349472/utils.py#L13-L14

Here comes my questions.

1. Is the model really working with depth vales from 0 to 1? My tests indicate that the model works in a range from 1 to 10. What am I missing?

2. The inversion of values in `DepthNorm` is intentional and represents any benefit compared to a simple scaling?

I have not commented on it before but I want to clarify this to train the model using my own data.

Thank you for your time.

**Comment by ialhashim** [comment]
Check out the prediction function for more details. "def predict". The range is in the inverted space. You can train the same network on almost any range you want and then start from there. Inversion advantage seems to be very minor after further testing.
