### ISSUE TITLE
tensorflow model

### ISSUE THREAD

**Issue by tomer5656** [ialhashim/DenseDepth#153]
can you please post how to build the tensorflow model?
Thanks, great work

**Comment by dinimar** [comment]
Use repository [keras_to_tensorflow](https://github.com/amir-abdi/keras_to_tensorflow) for conversion

**Comment by tomer5656** [comment]
I want to train the model as tensorflow model, so i need to build the mode before the training.

**Comment by dinimar** [comment]
@tomer5656 model defined in [model.py](https://github.com/ialhashim/DenseDepth/blob/master/model.py) and train script in [train.py](https://github.com/ialhashim/DenseDepth/blob/master/model.py). An instruction about how to train model is in README file.

**Comment by tomer5656** [comment]
but isn't model.py that you posted create keras model? i look to how to operate the create_model function with the model in the tensorflow folder

**Comment by dinimar** [comment]
to define model in tensorflow, you just need to find the same layers that defined in model.py in tensorflow. Or use [paper](https://arxiv.org/abs/1812.11941) to create a model architecture from scratch. There is no conversion tool for that you want to do. You have to write architecture by yourself.

**Comment by tomer5656** [comment]
but you published a tensorflow model in your repository, i just ask how to use it, its in the tensorflow folder

**Comment by ialhashim** [comment]
There is nothing special about the Tensorflow model. You train it like any other model.
