### ISSUE TITLE
QObject::moveToThread: Current thread (0x18a90c0) is not the object's thread (0x4fbe5f0). Cannot move to target thread (0x18a90c0)

### ISSUE THREAD

**Issue by chaotianjiao** [ialhashim/DenseDepth#155]
Hi~ when I run demo.py I got this error.
my enviroment is:
PySide2                5.15.1
PyOpenGL               3.1.5
PyGLM                  1.99.3
The OS is Ubuntu20.04
where should I modify my code?
Thanks~

**Comment by chaotianjiao** [comment]
@ialhashim  Hi, I have sloved this problem, How could I get the 3D cloud point information , like a .ply or .obj file?

**Comment by ialhashim** [comment]
You have to write a OBJ or PLY writer. Since we are using python it should be easy to find ones online.

**Comment by Varat7v2** [comment]
@chaotianjiao I am getting the same error. How did you solve the problem? Thanks in advance.
