### ISSUE TITLE
Model load and save errors

### ISSUE THREAD

**Issue by progwiz** [ialhashim/DenseDepth#156]
Hello, I am running the train.py file in python 3.7.5 with tensorflow-gpu version 1.13.1 and keras 2.2.4. The model load procedure seems to fail with the inbuilt 3.7.5 libraries. And downgrading h5py module to 2.10.0 loads the model successfully but fit_generator() throws an error while saving the model.

Can you please detail the environment you are using? Particularly the python version and the h5py module version. Or if possible the complete requirements.txt file? 
It would be really helpful. Thanks!

**Comment by ialhashim** [comment]
You can track down the versions of these packages of last year and just go with that.
