### ISSUE TITLE
How could I use this to turn live 2D video from camera into 3D video

### ISSUE THREAD

**Issue by lukebotticelli** [ialhashim/DenseDepth#158]
Hello,

I am a novice with machine learning. I am working on a project that needs to turn live 2D video from a camera into 3D video that can be seen on a VR headset. Can this algorithm be used for that?

**Comment by ialhashim** [comment]
You could do it frame by frame. However these single image depth estimation methods are not very accurate. Also what you get is a 2.5D image.. it has lots of missing geometry.

Other approaches work on multiple input images (videos) like this https://www.youtube.com/watch?v=MrKrnHhk8IA
