### ISSUE TITLE
Not JSON Serializable

### ISSUE THREAD

**Issue by bradasteiner** [ialhashim/DenseDepth#16]
Hi, when training on a custom dataset I am getting an error when it tries to save the model checkpoint with `keras.callbacks.ModelCheckpoint`. The error is ```raise TypeError('Not JSON Serializable: %s' % (obj,))
TypeError: Not JSON Serializable: ?``` Any thoughts?

**Comment by ialhashim** [comment]
This is a known Keras bug.. unfortantly they haven't solved it yet. You can instead follow the instructions here: https://github.com/keras-team/keras/issues/9342#issuecomment-396056333
