### ISSUE TITLE
Preferable image resolution or aspect ratio?

### ISSUE THREAD

**Issue by balintlaczko** [ialhashim/DenseDepth#161]
Hey! Thanks for the great work. I just tried the nyu network out, and I had a problem running my 1920x1080px video-frames through it. Basically under the `model.predict` stack I get complaints about mismatching shapes. If I use a 640x480px input (like your example pics) everything works fine.
My question: is the model limited to that exact 640x480px resolution, or is it the 3:2 ratio which it needs? (Or something else?)

Thanks a lot!

**Comment by ialhashim** [comment]
You can resize the images to the expected resolution. While you could in theory train the network to handle any size, the performance is generally tied up to what the network was trained on.

**Comment by balintlaczko** [comment]
Thanks, that actually makes perfect sense!
