### ISSUE TITLE
Test.py save images individually instead of in grid

### ISSUE THREAD

**Issue by Aiyush-G** [ialhashim/DenseDepth#164]
Hi, 

I hope that you are well, this is a great tool that you have created here. Unfortunately, I am a bit of a python noob and was hoping that you could help me adjust the end of test.py so that the depth maps are saved individually instead of put together into a grid. 

I look forward to your reply.

Kind Regards
Aiyush

**Comment by Aiyush-G** [comment]
I have come up with this but I'm sure there is a more efficient way. If so please reply:
`import os
import glob
import argparse
import matplotlib

# Keras / TensorFlow
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '5'
from keras.models import load_model
from layers import BilinearUpSampling2D
from utils import predict, load_images, display_images, save_images
from matplotlib import pyplot as plt

# Argument Parser
parser = argparse.ArgumentParser(description='High Quality Monocular Depth Estimation via Transfer Learning')
parser.add_argument('--model', default='nyu.h5', type=str, help='Trained Keras model file.')
parser.add_argument('--input', default='examples/*.png', type=str, help='Input filename or folder.')
args = parser.parse_args()

# Custom object needed for inference and training
custom_objects = {'BilinearUpSampling2D': BilinearUpSampling2D, 'depth_loss_function': None}

print('Loading model...')

# Load model into GPU / CPU
model = load_model(args.model, custom_objects=custom_objects, compile=False)

print('\nModel loaded ({0}).'.format(args.model))

# Input images
print ('Inputs for args:', type(glob.glob(args.input)), str(glob.glob(args.input)))
print ('Starting Itterations')
array_input = glob.glob(args.input)
for x in range (len(array_input)):
    print ('Itteration',x,'name',array_input[x])
    single_image = array_input[x]
    # Input Images
    inputs = load_images(glob.glob(single_image))
    
    #inputs = load_images( glob.glob(args.input) )
    print ('Input Type:', type(inputs))
    print('\nLoaded ({0}) images of size {1}.'.format(inputs.shape[0], inputs.shape[1:]))
    # Compute results

    print ("[COMPUTING RESULTS STARTED]")
    outputs = predict(model, inputs)
    print ("[COMPUTING RESULTS FINISHED]")

    #matplotlib problem on ubuntu terminal fix
    #matplotlib.use('TkAgg')   

    # Display results
    '''
    viz = display_images(outputs.copy(), inputs.copy())
    plt.figure(figsize=(10,5))
    plt.imshow(viz)
    plt.savefig('test.png')
    plt.show()
    '''

    # Save Results
    save_images((str(x)+'.png'), outputs.copy())
    print ("[IMAGE(S) SAVED]")

print ('[ALL FINISHED]')
`

**Comment by karndeb** [comment]
Hi @Aiyush-G There is a better way to do this. Dont return the montage in the display function in utils and loop through the images that you get to save them individually

**Comment by Aiyush-G** [comment]
Hi @karndeb thanks for the response , I really appreciate you getting back to me. I am slightly bookish and would really appreciate if you could help me adjust a copy of the code.

Thanks
AG
