### ISSUE TITLE
no size change after optimizing using tensor RT

### ISSUE THREAD

**Issue by UcefMountacer** [ialhashim/DenseDepth#167]
Hi,

I tried optimizing this model using tensor rt. However there is no change in the size of the model nor the inference time which is odd. Do someone have an idea about this. Are there some models that can't be optimized using trt.

PS: I tried fp16 and int8

**Comment by ialhashim** [comment]
I don't have experience in Tensor RT. Its best to ask people in the NVIDIA forums.
