### ISSUE TITLE
Why PyTorch code does't train correct?

### ISSUE THREAD

**Issue by tomashlehmann** [ialhashim/DenseDepth#170]
Hello, 
I tried to train model by PyTorch "experimental" code which is attached in /PyTorch directory, but it doesn't train like it should. 
After every epoch results are pretty same and also far away from the ones from publication. 
For example results after 20th epoch of training:
a1=0.56, a2=0.83, a3=0.93, rel=0.25, rms=1, log_10=0.11

Did anyone try to train that? What can be a reason of wrong results?

**Comment by ialhashim** [comment]
The PyTorch code is experimental. You are better off simply looking at it and starting from scratch writing your own model code.
