### ISSUE TITLE
How to get point cloud

### ISSUE THREAD

**Issue by Alek-dr** [ialhashim/DenseDepth#172]
Hello!
I tried to get point cloud like in KITTI dataset
I see point cloud in demo.py but it's kind of opengl stuff

Pls, give at least an idea how to get it
Thanks

**Comment by ialhashim** [comment]
Take a look how "posFromDepth" is used https://github.com/ialhashim/DenseDepth/blob/70633175f7f3a1ba5443075cee21ef0520e2d55c/demo.py#L342

You have to precompute some coordinates (xx,yy) and multiply by that.
