### ISSUE TITLE
Eigen test set

### ISSUE THREAD

**Issue by mazenmel** [ialhashim/DenseDepth#174]
Hi,
Thanks for sharing your great work. I have a question regarding NYUV2 test set that you used to evaluate your model. Is it the same one you provided in this project? and if so how do you account for invalid pixels seen in the original test set of Eigen et al. where they did not consider those pixels for evaluation, and as far as I know most paper reports their results based on that original set with the invalid pixels. Thank you!

**Comment by ialhashim** [comment]
The evaluation set is based on existing work. For better details on evaluation take a look at our newer paper AdaBins.
