### ISSUE TITLE
missing one layer

### ISSUE THREAD

**Issue by abubakrsiddq** [ialhashim/DenseDepth#180]
**Tensorflow2 code**
```
class UpscaleBlock(Model):
    def __init__(self, filters, name):      
        super(UpscaleBlock, self).__init__()
        self.up = UpSampling2D(size=(2, 2), interpolation='bilinear', name=name+'_upsampling2d')
        self.concat = Concatenate(name=name+'_concat') # Skip connection        
        self.convA = Conv2D(filters=filters, kernel_size=3, strides=1, padding='same', name=name+'_convA')
        self.reluA = LeakyReLU(alpha=0.2)
        self.convB = Conv2D(filters=filters, kernel_size=3, strides=1, padding='same', name=name+'_convB')
        self.reluB = LeakyReLU(alpha=0.2)
    
    def call(self, x):        
        b = self.reluB( self.convB( self.reluA( self.convA( self.concat( [self.up(x[0]), x[1]] ) ) ) ) )
        return b 

```

**Saved model**
[<layers.BilinearUpSampling2D at 0x7f303b213710>,
 <tensorflow.python.keras.layers.merge.Concatenate at 0x7f303b213990>,
 <tensorflow.python.keras.layers.convolutional.Conv2D at 0x7f303b213e90>,
 <tensorflow.python.keras.layers.convolutional.Conv2D at 0x7f303b1a35d0>,
 <tensorflow.python.keras.layers.advanced_activations.LeakyReLU at 0x7f303b1a3cd0>]

In the saved model of tensorflow 2 model there is extra layer (reluA) which is missing in the save keras model

**Comment by ialhashim** [comment]
If you create a pull request I will be happy to merge a fix.
