### ISSUE TITLE
Question about the inconsistency between train set and test set.

### ISSUE THREAD

**Issue by Boltzmachine** [ialhashim/DenseDepth#184]
In the train set, the pixels of depth images are small (approximately 0~1), while in the test set the values are large (> 1000). Can you tell me how to convert them to the same format? Which one is the original depth number? I found many people had the same question but it was has not been solved yet.

**Comment by ialhashim** [comment]
It doesn't matter, in the end it is normalized from 0 to 1. And then to get the "real" depth values you simply multiply by the maximum depth (in meters, e.g. NYU is 10meters) to get the distance.
