### ISSUE TITLE
pretrained model download error

### ISSUE THREAD

**Issue by kkyes1210** [ialhashim/DenseDepth#185]
we want to download pre-trained models, but if we try to download them, there is an error(access denied).

p.s) attach the photo
<img width="615" alt="403error" src="https://user-images.githubusercontent.com/81374161/124423373-f8e18580-dd9f-11eb-8727-6ea08aed972a.PNG">

**Comment by kulalsk2** [comment]
Yeah Even I am facing the sane issue.

**Comment by ialhashim** [comment]
Try this link https://drive.google.com/file/d/19dfvGvDfCRYaqxVKypp1fRHwK7XtSjVu/view?usp=sharing
