### ISSUE TITLE
pretrained model download error2

### ISSUE THREAD

**Issue by kkyes1210** [ialhashim/DenseDepth#187]
I downloaded the nyu pretrained model well. Thank you.

The outdoor model pre-trained model also cannot be downloaded. I'd really appreciate it if you could download it!

<img width="618" alt="error2" src="https://user-images.githubusercontent.com/81374161/124687005-15500000-df0f-11eb-9c75-78eb48a5b5a9.PNG">

**Comment by rajrohanyadav** [comment]
Getting the same error for nyu.h5 as well.

![image](https://user-images.githubusercontent.com/16662291/124695186-5987d400-df00-11eb-9b78-1ef8a8efd92b.png)

**Comment by necronomican** [comment]
Yes same here

**Comment by emad555** [comment]
Is is solved yet?

**Comment by kkyes1210** [comment]
No, not resolved yet ㅠㅠ

**Comment by ialhashim** [comment]
Both models are now uploaded to Google drive (check README).

**Comment by emad555** [comment]
Found it, thank you!
https://drive.google.com/u/0/uc?id=19dfvGvDfCRYaqxVKypp1fRHwK7XtSjVu&export=download
