### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.keras.topology'

### ISSUE THREAD

**Issue by BlueveryPi** [ialhashim/DenseDepth#196]
`ModuleNotFoundError: No module named 'tensorflow.keras.topology`
happens when trying to run layer.py in colab.

solution: replace 
` from tensorflow.keras.topology import Layer, InputSpec `
from line 1 of layer.py to 
` from tensorflow.keras.layers import Layer, InputSpec `

**Comment by ialhashim** [comment]
Seem related to https://github.com/ialhashim/DenseDepth/pull/197
