### ISSUE TITLE
ground truth image

### ISSUE THREAD

**Issue by wasona** [ialhashim/DenseDepth#199]
Hello Mr.Ibraheem,
please how can I download the ground truth images for NYUv2 dataset?? 

And for the NYU v2 images depth map it is on black and white?? or colors?

**Comment by ialhashim** [comment]
https://drive.google.com/drive/folders/1TzwfNA5JRFTPO-kHMU___kILmOEodoBo

**Comment by andreaceruti** [comment]
Hi @ialhashim ! I am trying to load the Nyuv2 dataset and I have found this issue. Since the dataset is too heavy for my poor pc can you explain me what does your link contains about nyuv2? I am searching for aligned RGB and depth images and also their ground truth annotations
