### ISSUE TITLE
How to get the real depth value from Kitti dataset?

### ISSUE THREAD

**Issue by rsj007** [ialhashim/DenseDepth#200]
Hi, ialhashim
I want to test the depth precision (in meters) for DenseDepth, not the disparity error rate. My opinion is to calculate by the formula "z = b*f/d". But I can't find the depth groundtruth of Kitti stereo dataset and the camera information. Could you give me some guides? Thanks!!!

**Comment by Zhangwenyao1** [comment]
have you solved it？
Can you give me some advice？
