### ISSUE TITLE
test.py error: tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: 

### ISSUE THREAD

**Issue by glenn-jocher** [ialhashim/DenseDepth#21]
I verified that test.py works with the images in the examples folder. After this I created a new folder called 'images', placed one image inside and ran `python3 test.py --input 'images/*.jpg'`

```bash
Using TensorFlow backend.
Loading model...
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

Model loaded (nyu.h5).

Loaded (1) images of size (4032, 3024, 3).
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    outputs = predict(model, inputs)
  File "/content/DenseDepth/utils.py", line 12, in predict
    predictions = model.predict(images, batch_size=batch_size)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1169, in predict
    steps=steps)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,1664,252,188] vs. shape[1] = [1,256,252,189]
	 [[{{node up1_concat/concat}}]]
	 [[{{node conv3/BiasAdd}}]]
Done (44.03s)
```

The image I used is here:
![IMG_8507](https://user-images.githubusercontent.com/26833433/57402889-96e55f80-71d8-11e9-9e3d-10ea70e44571.jpg)

**Comment by ialhashim** [comment]
The pre-traind network assumes images of size 480x640x3 I believe if you crop and resize the image accordingly it should work. Keep in mind that the model was trained on indoor scenes so the output might be disappointing for such a scene.

**Comment by glenn-jocher** [comment]
@ialhashim ah yes, it works after I crop to 480x640.

Does the KITTI dataset expect a certain image shape as well?

**Comment by ialhashim** [comment]
Images should be 384 x 1248 x 3 for KITTI.

**Comment by bradasteiner** [comment]
For transfer learning from the kitti dataset, should we provide images that are 384x1248 as well? I noticed that there is no code related to kitti in data.py

**Comment by ialhashim** [comment]
You can provide any dimension you prefer when training from scratch. In the end during evaluation we resize the output to fit the ground truth anyways. The problem with Kitti is that it has many different sizes. And densenet prefers dimensions divisible by 32.
