### ISSUE TITLE
TypeError:montage() got an unexpected keyword argument 'multichannel'

### ISSUE THREAD

**Issue by ATTUNE-code** [ialhashim/DenseDepth#220]
Hello, I have encountered this problem, how to solve it, thank you!
![image](https://user-images.githubusercontent.com/70506603/230713392-ff75f6ae-b7c1-4fd1-8543-767767a4426b.png)

**Comment by scarletshroud** [comment]
Can you provide the solution of this problem, please?

**Comment by ATTUNE-code** [comment]
Sorry for replying to the message so late. I remember it was a problem with the scikit image version, but I forgot the specific version.

**Comment by ATTUNE-code** [comment]
> 

Sorry for replying to the message so late. I remember it was a problem with the scikit image version, but I forgot the specific version.
