### ISSUE TITLE
About the depth completion.

### ISSUE THREAD

**Issue by DarryO** [ialhashim/DenseDepth#24]
Thanks for your great contribution.
I am doing experiments on my own data recently. The model works well. But one problem is that there is large gap(meters) between the "ground truth" data(dense depth generated by "fill_depth_colorization.py") and real depth(I see this after I project pixels with depth to 3d word, and compare the point cloud with the lidar data.)

So, I decide to try some other depth completion methods. But before that, I wonder why you chose "Colorization using optimization" as the method in your model? Any important reason?

**Comment by DarryO** [comment]
How about using a deep model listed in [Kitti benchmark](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion)

**Comment by ialhashim** [comment]
The method have been used by others and its a very simple depth completion technique. If you apply a modern depth compilation method you might risk attributing your success to such method and therefore need to test all other methods given this new clean data. Where as the colonization method is very old amd can be a fair baseline. However I would be interested to know the extent of such clean data on our performance.
