### ISSUE TITLE
fill_depth_colorization.py question

### ISSUE THREAD

**Issue by aaronjie** [ialhashim/DenseDepth#28]
Hi, Ibraheem, question again : )
I tried to convert sparse depth map to dense depth map using your's python version of fill_depth_colorization.m in NYU v2 dataset toolkits. However, I found something strange. 
my test code is as following:

from fill_depth_colorization import *
from PIL import Image
if __name__ == '__main__':
    p1 = 'kitti_raw_data/2011_09_26/2011_09_26_drive_0001_sync/image_02/data/0000000005.png'
    p2 = 'train/2011_09_26_drive_0001_sync/proj_depth/groundtruth/image_02/0000000005.png'
    img1 = np.array(Image.open(p1))
    img2 = np.array(Image.open(p2))
    dense = fill_depth_colorization(img1, img2)
    print((img2.min(), img2.max()), (dense.min(), dense.max()))

output: (0, 21733) (1365.0, 21733.0)

It seems the minimal value is changed to non-zero (0 to 1365.0) after the inpainting method. I am not sure whether this is normal. 
I noticed that you use the reciprocal of the depth, so non-zero is a must?
Thank you.

**Comment by ialhashim** [comment]
Try visualizing the before and after the fill call and see if the depths are reasonable. 

The filling code indeed tries to fill all zero values with something since the assumption is that zero values are missing.

**Comment by aaronjie** [comment]
Hi, Ibraheem, thanks.
I tried to convert sparse to dense, however, it is a bit slow (cost more than 30 seconds).
In README.md, I found "
For our experiments, we used our Python re-implmentaiton of the Matlab code provided with NYU Depth V2 toolbox. **The entire 80K images took 2 hours on an 80 nodes cluster for inpainting**. For our training, we used the subset defined here. "

I wonder the meaning of "an 80 nodes cluster for inpainting",  thanks again.

**Comment by aaronjie** [comment]
> Try visualizing the before and after the fill call and see if the depths are reasonable.
> 
> The filling code indeed tries to fill all zero values with something since the assumption is that zero values are missing.

Hi, Ibraheem, thanks.
I tried to convert sparse to dense, however, it is a bit slow (cost more than 30 seconds).
In README.md, I found "
For our experiments, we used our Python re-implmentaiton of the Matlab code provided with NYU Depth V2 toolbox. The entire 80K images took 2 hours on an 80 nodes cluster for inpainting. For our training, we used the subset defined here. "

I wonder the meaning of "an 80 nodes cluster for inpainting", thanks again.

**Comment by ialhashim** [comment]
I just mean I ran the filling procedure of the entire dataset on a cluster of machines in order to finish them at a reasonable time. If you don't have access to such resources I would recommend running the matlab code with a parallel for loop or looking for other faster python implementations found online.

**Comment by aaronjie** [comment]
> I just mean I ran the filling procedure of the entire dataset on a cluster of machines in order to finish them at a reasonable time. If you don't have access to such resources I would recommend running the matlab code with a parallel for loop or looking for other faster python implementations found online.

Thank you very much.

**Comment by TimbusCalin** [comment]
@aaronjie  Did you manage to use and verify the results of the inpainting conversion method? Could you give me some hint as to how to proceed?

    image_rgb = cv2.imread('C:\\Users\\Calin\\Desktop\\test_inpaint\\0000000005_rgb.png')[:,:,::-1]
    image_depth = cv2.imread('C:\\Users\\Calin\\Desktop\\test_inpaint\\0000000005_rgb.png',0)
    image_depth_filled= fill_depth_colorization(imgRgb=image_rgb,imgDepthInput=image_depth,alpha=1)

Is this the correct way to proceed?
