### ISSUE TITLE
Could we perform SLAM with this demo??

### ISSUE THREAD

**Issue by abdur4373** [ialhashim/DenseDepth#30]
Hello @ialhashim @cclauss I want to perform SLAM with predicted depth, As you have show 3D image so could we perform SLAM from single images using your demo.py.
Secondly that 3D map is generated from single image or sequence of images.
Thank you.

**Comment by ialhashim** [comment]
You can compute the point cloud following the code in the demo. Then use something like this `https://github.com/simondlevy/BreezySLAM` which I fond by Googling SLAM and Python. I don't have anything ready for SLAM unfortunately.
