### ISSUE TITLE
Generating depth maps with "I" mode instead of RGB

### ISSUE THREAD

**Issue by AbigailFernandes** [ialhashim/DenseDepth#31]
The depth maps generated by test.py are currently in RGB format. How do I get them to be in "I" mode, Intensity format. https://pillow.readthedocs.io/en/5.1.x/handbook/concepts.html#concept-modes

**Comment by ialhashim** [comment]
If you look at line 34 `outputs = predict(model, inputs)` these outputs are in terms of distance from camera per pixel. They are normalized to the range `[0,1]` which you can convert to the range you like (e.g. 10 meters for NYU).
