### ISSUE TITLE
Could you please list the version of all the required packages

### ISSUE THREAD

**Issue by tlsshh** [ialhashim/DenseDepth#33]
Hello ~ Could you please list the version of all the required packages in order to run with PyTorch. I think the version of PyTorch is the most important.

Thanks a lot!

**Comment by ialhashim** [comment]
Hi @tlsshh, just a couple of points:

- The PyTorch version is just a reference implementation. The trained weights and the best results were trained on the default Keras version.
- I tested the PyTorch by simply creating a new conda environment and simply running `conda install -c pytorch pytorch`. I think at that time it was already PyTorch 1.x.
