### ISSUE TITLE
How to generate a gray depth map？

### ISSUE THREAD

**Issue by Jzz1943** [ialhashim/DenseDepth#34]
Hi，Ibraheem.
First, I want to say this is a very amazing algorithm that help me a lot，thank you！
I know some depth values of the raw NYU depth map (in meter) is missing which need to be filled by the Matlab code provided with NYU Depth V2 toolbox. 
**Now, I have a question, after filled, how to convert the depth in meter to gray image (extracted from the 4.1G zip that you provided)?**
depth_gray = int(depth_in_meter / max(depth_in_meter) * 255)? Or other coverting way？

**Comment by ialhashim** [comment]
I believe so, but you can avoid that if you have the space. Simply save all filled results as .mat or numpy files with floating points in the range of 0 to 1. You might need to slightly modify the data loader code to account for that.

**Comment by Jzz1943** [comment]
I have understood. Thank you very much！
