### ISSUE TITLE
Inter-frame consistency

### ISSUE THREAD

**Issue by mihaibujanca** [ialhashim/DenseDepth#4]
Hi, thank you for releasing your work - the results look excellent!

I am looking at trying to process videos and getting quite a lot of flickering across different frames. I was wondering if you have any suggestion on what might help with getting more consistency across frames.

The literature (mainly in style transfer) seems to be pointing towards ConvLTSM as the choice to achieve better consistency

**Comment by ialhashim** [comment]
Thanks for your interest! we are also looking into video and obviously at this point there is a lot of flickering. I think several works I mention in the paper are trying to produce better depth estimation using two or more frames, e.g. [this](https://arxiv.org/abs/1806.01260) and [this](https://arxiv.org/abs/1808.01900), or for small motion maybe use something like [this](https://www.youtube.com/watch?v=DTL6f9C_GlU).

I am not familiar with ConvLTSM. From my experience working on this project it can be very tricky to assume much about what is being learned. The best case is that the current model can be used to predict two or more frames and have another network figure out the correspondence and produce a more spatially and temporally accurate depth map than the individual results. In the worst case, the model is just really good at memorization at the individual frame level, which would be a disappointing conclusion. Looking at the results for the synthetic Unreal test set, its obvious all existing methods, including mine, have a long way to go for better generalization on single frames.

**Comment by mihaibujanca** [comment]
Thanks for the answer and suggestions! Currently reading the literature on style transfer consistency for videos: [link](https://cs.stanford.edu/people/jcjohns/papers/eccv16/JohnsonECCV16.pdf), [link](https://medium.com/coinmonks/real-time-video-style-transfer-fast-accurate-and-temporally-consistent-863a175e06dc)

**Comment by OmarLaz97** [comment]
Hi @mihaibujanca, i am interested in using a video also, did you have any luck solving the flickering issue ?

**Comment by mihaibujanca** [comment]
> Hi @mihaibujanca, i am interested in using a video also, did you have any luck solving the flickering issue ?

There are a couple of techniques out there but I haven't done anything further on this
