### ISSUE TITLE
depth while training

### ISSUE THREAD

**Issue by saishankarn** [ialhashim/DenseDepth#41]
In NYU_BasicAugmentRGBSequence class in data.py, the depth image pixel values are divided by 255 and multiplied by maxDepth. Why are the depth values divided by 255 ? I haven't used NYU depth dataset. Is that how the depth is given in NYU Depth dataset ?

**Comment by ialhashim** [comment]
That's how it is the in filled depth images (single channel image values from 0 to 255). 

If you recompute the depth filling step you can define your own range (provided you save it in a file format that supports it).

**Comment by saishankarn** [comment]
Also, where can I get the crop npy file?

**Comment by ialhashim** [comment]
For NYU its in the `nyu_test.zip` file.
