### ISSUE TITLE
Test my pictures

### ISSUE THREAD

**Issue by cww123456789** [ialhashim/DenseDepth#42]
Hello, I used  test.py to test the indoor photos I took, but the output depth map had poor effect, and even the opposite situation occurred. How can I improve his accuracy?Thank you.

**Comment by ialhashim** [comment]
Could you provide an example or more details?

Keep in mind the generalization performance (quality of estimated depth on images not very similar to training dataset) is still overall not that good.

**Comment by cww123456789** [comment]
I tested four images.The two on the left are pictures of plasterwork and jars taken by the camera, and the two on the right are a composite of 3dsmax.
![Figure_1](https://user-images.githubusercontent.com/45026311/62196592-e8a11e80-b3b0-11e9-9d5f-8447247e5793.png)

**Comment by ialhashim** [comment]
These images are very different from NYU (the training data). It is expected to obtain such results for most CNN depth estimation methods. If you find a method that performs better on these challenging images let me know, I would interested to compare against them.

**Comment by cww123456789** [comment]
Well, thank you very much for your help. Good luck
