### ISSUE TITLE
Pre-processing of depth ground truth

### ISSUE THREAD

**Issue by arvkr** [ialhashim/DenseDepth#44]
Thank you for the code. I am planning to finetune the NYUv2 pretrained model on my own kinect dataset. I have a question about the pre-processing done to the depth ground truth data.

 From my understanding, your NYUv2 keras model takes 480x640 images (each pixel a 0-255 uint8 value) as input depth ground truth data(from the ~4 GB nyu-data.zip files). However, your python re-implementation of the depth infilling method gives as output depth values between 0 - 1 float. 

It would be great if you can let me know how did you exactly convert the 0-1 float to 0-255 uint. Did you directly multiply by 255 and convert to uint8? Or did you something like,

255*((depth_infilling_output - Min(depth_infilling_output))/max(depth_infilling_output))

Thank you

**Comment by arvkr** [comment]
My bad, upon better checking the nyu-data.zip files, I realized the model takes 480x640 images float32 data. So I'm guessing It would be okay if I directly feed the output of fill_depth_colorization.py to your model without any additional pre-processing?

**Comment by ialhashim** [comment]
Yes.

**Comment by ialhashim** [comment]
I guess the standard thing is to print the minimum and maximum of both tests and see if maybe zeros are throwing things off or such. It could be just a visualization issue or some small mistake in the ranges. Try to step by step print the values of the data before it is sent to the training loop.
