### ISSUE TITLE
How do you calculate the surface normal from depth map?

### ISSUE THREAD

**Issue by vinjohn** [ialhashim/DenseDepth#45]
Hi,
Nice work! we find it work consistently well with indoor and outdoor scenes.
I wonder how you compute the surface normal from depth map in fig. 4 of the paper?

Thanks!

**Comment by ialhashim** [comment]
You can try this (maybe in a Jupyter notebook) on the depth data (without any normalization):
```
def compute_normals(y):
    dx, dy = np.gradient(y[:,:,0])
    dz = np.ones_like(dy)
    dx = dx * 25
    dy = dy * 25
    n = np.linalg.norm(np.stack((dy, dx, dz), axis=-1), axis=-1)
    d = np.stack((dy/n, dx/n, dz/n), axis=-1)
    return (d + 1) * 0.5
```
This is a quick dirty way, you might want to also look at computing it in a more reasonable matter since for Kinect depth data the normals are very challenging.
