### ISSUE TITLE
Size of trained model

### ISSUE THREAD

**Issue by abinramapuram** [ialhashim/DenseDepth#46]
I have trained the network using my kitti and nyu dataset. And my saved model has size of 344 mb. But the downloaded pretrained model only weights half the size. ie,172 mb. Why that difference?

**Comment by ialhashim** [comment]
Keras is saving the optimizer's weights (https://stackoverflow.com/a/50200466/463409). If you specify the option `include_optimizer=False` I believe you should get a smaller file.
