### ISSUE TITLE
[QUESTION]: Hints on: using the model trained on KITTI for a different dataset

### ISSUE THREAD

**Issue by MTDzi** [ialhashim/DenseDepth#47]
Hi,

Great work, really impressive!

I would like to use the pre-trained model (on the KITTI dataset) on images from the [Drive360 dataset](http://people.ee.ethz.ch/~heckers/Drive360/) and I was wondering if you had any suggestions on how to best prepare those images to get the best possible prediction using the DenseDepth model.

Here's an example image:
![image](https://user-images.githubusercontent.com/31838868/62778076-9ac29f80-baaf-11e9-821d-35e5a714f433.png)
its shape is: (1080, 1920, 3) whereas the ones in the KITTI dataset are (if I'm not mistaken): (370, 1224, 3).

My initial thought was to crop the 1080x1920 images to extract central 370x1224 rectangle -- what dou you think?

**Comment by ialhashim** [comment]
You probably should resize the width to 1224 and then center crop the height to 370 from whatever the height it becomes after resizing. 

You can also simply just resize to 370x1224 as a first experiment then try different resizing and cropping strategies.
