### ISSUE TITLE
KITTI raw or KITTI depth?

### ISSUE THREAD

**Issue by cgebbe** [ialhashim/DenseDepth#51]
First of all thank you very much for your contribution. One question: Have you used the KITTI raw or the KITTI depth dataset as your basis for inpainting?

While the README.md states "KITTI: copy the *raw* data", [this issue](https://github.com/ialhashim/DenseDepth/issues/26) indicates that KITTI depth was used...

**Comment by ialhashim** [comment]
Whats the difference?

**Comment by cgebbe** [comment]
KITTI raw refers to the ground truth, which is created by simply projecting one 360° LIDAR scan into the camera image.
http://www.cvlibs.net/datasets/kitti/raw_data.php
https://github.com/nianticlabs/monodepth2/blob/master/datasets/kitti_dataset.py#L65

KITTI depth refers to a refined ground truth, which was created by Uhrig et. al through aggregation and automatic filtering of KITTI raw. 
http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction
http://www.cvlibs.net/publications/Uhrig2017THREEDV.pdf

**Comment by ialhashim** [comment]
I believe it is KITTI depth

**Comment by cgebbe** [comment]
Ok, thanks!
