### ISSUE TITLE
Get the depth information 

### ISSUE THREAD

**Issue by Zhu-Jinkuan** [ialhashim/DenseDepth#52]
Can you tell me how to get the real depth information through the output of the model. Is the output equal to the disparity map? For example, if I use the trained model to test a CitySpace picture whose size is 2048x1024. Should I resize the output(1024x512) to 2048x1024 first, and then use the formula : 
                         depth = 0.209313 * 2262.52/(2048 * disparity)  
to get the depth map? 
Thanks for your brilliant work.

**Comment by ialhashim** [comment]
Are you just testing the trained KITTI model? I believe you need to resize the image to (370 x 1224 x 3) (that is height x width x channels). Then apply the formula `80/y` where `y` is the output of the trained model. This should give you the depth for each pixel in the range 0 to 80 meters.

**Comment by Zhu-Jinkuan** [comment]
Thanks for your rapid reply! Actually I want test the transfering ability of the model by test the CitySpace demo using the trained KITTI  model. And now I meet two problems. 
First when I directly input a CitySpace picture without resizing, the code seems to work well. But when I resize it to (370, 1224, 3) as you mentioned in the reply, it gets erros. 
Another problem is that the output is around 0.06 ~ 0.49 (without resizing the pircture) So maybe the formula 80 * y has a more reasonable result than 80/y? 
Thanks agian for writting back.

**Comment by ialhashim** [comment]
What function are you using to get the depth? the one at `utils.predict` already does the normalization step. So indeed the output will only need to be `80 * y` (provided you give it the correct range values `(minDepth=1, maxDepth=80)`.

**Comment by Zhu-Jinkuan** [comment]
Oh I think I get it, many thanks for your reply !
