### ISSUE TITLE
ImportError: Cannot load backend 'TkAgg'

### ISSUE THREAD

**Issue by EdisonBing** [ialhashim/DenseDepth#53]
Currently running densedepth through docker image(provided below) and receive error when running test.py after downloading training set. Any idea what could be going on?

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

OS:Ubuntu 16.04
docker image:
https://hub.docker.com/r/aragorn1025/dense_depth

**Comment by ialhashim** [comment]
Could be related to this?

https://github.com/ialhashim/DenseDepth/commit/e8f58f6133a2d3541eafb8fa693ca6037d5860e6

**Comment by EdisonBing** [comment]
indeed it was commenting out resolved the issue, thank you
