### ISSUE TITLE
Bilinear upsampling custom layer

### ISSUE THREAD

**Issue by arvkr** [ialhashim/DenseDepth#55]
Great work, it was useful for my work!

In the keras model , you have carried out Bilinear upsampling via a Keras custom layer implementation. Could you let me know why you have not used the inbuilt [keras.layers.UpSampling2D layer](https://keras.io/layers/convolutional/) ?

Thank you

**Comment by ialhashim** [comment]
I believe the feature to select the interpolation type was not available when I first started (it might have been only nearest).

Anyways, I think you can use it no problem. I would be worried to make the change now and cause unintended consequences.

**Comment by arvkr** [comment]
Okay thanks for the information!
