### ISSUE TITLE
About nyu_data.zip

### ISSUE THREAD

**Issue by jzbontar** [ialhashim/DenseDepth#56]
Hello Ibraheem, thanks for open sourcing your code.

I have a question about how the NYUv2 50k training dataset was constructed. Did you generate it from the NYUv2 raw dataset yourself? How did you select the scenes? How did you choose the 50k subset? Would it be possible to provide code that generated nyu_data.zip? Thanks!

**Comment by ialhashim** [comment]
The exact data in that zip file are from here https://github.com/JunjH/Revisiting_Single_Depth_Estimation

We also tried it by filling out the missing values from NYUv2 where we get around 300K images and take a subset of 50K. The results are very similar.
