### ISSUE TITLE
RGBD Player Displays Image on Flat Plane

### ISSUE THREAD

**Issue by ShreyJ1729** [ialhashim/DenseDepth#57]
When I run the demo.py program, the RGBD player shows the images I load or the webcame as a flat frame. Issue not fixed upon clicking refresh.

<img width="689" alt="DenseDepth PCL" src="https://user-images.githubusercontent.com/23284483/65014625-d2114100-d8e4-11e9-9a0a-fb622e56f80f.PNG">

**Comment by ialhashim** [comment]
Did you load the model (after downloading it). Check the console/terminal for any errors.
