### ISSUE TITLE
According maxDepthVal inloss.py

### ISSUE THREAD

**Issue by resindraburiza** [ialhashim/DenseDepth#58]
Hello,
good evening. Firstly, I would like to thank you for releasing your code. It could be a lifesaver for me to learn more about learning-based method.

I want to ask about maxDepthVal in loss.py's argument input. In the NYU_BasicAugmentRGBSequence it is stated that maxVal is 1000.0 which I believe is 1000 cm. Is it correct? But, for calculation of SSIM, why do you use 1000.0/10.0 as maxDepthVal? I wish that you would like to help me understand this even though this might be just a very simple question. Thank you very much.

Best,
Resin

**Comment by ialhashim** [comment]
Looking at https://github.com/ialhashim/DenseDepth/blob/master/data.py#L106

You can see that the data is 'normalized' using the `maxDepth / depthValue`. So the maximum is not 1000 anymore but rather 1000 / minimum expected depth.

**Comment by resindraburiza** [comment]
thank you for very fast reply. I really appreciate it. now I see that in the training, the inverse depth is used. By the way, from where did you get the minimum expected depth = 10 information? Thank you so much.

**Comment by ialhashim** [comment]
I think it is mentioned in the NYU original page

**Comment by resindraburiza** [comment]
Thank you! I'll check it out soon.
