### ISSUE TITLE
Porting pretrained model to Tensorflow Lite

### ISSUE THREAD

**Issue by Angtrim** [ialhashim/DenseDepth#61]
I'm trying to convert the pretrained model (nyu.h5) using the TfLite converter for keras models.
I'm having no luck and I'm getting the error:

` E tensorflow/core/grappler/grappler_item_builder.cc:656] Init node conv1/conv/kernel/Assign doesn't exist in graph`

I've also tried to retrain the models (both the Keras one and the Tensorflow one) with no success. 

I just need to freeze the model, port it on TFLite and perform the inference on mobile.
Can someone please tell me if there is a chance I can port this model on mobile?

Thank you.

**Comment by ialhashim** [comment]
Unfortunately I don't have much experience with that. Keep in mind the model might be too big for mobile.
