### ISSUE TITLE
The pretrained model for testing other dataset?

### ISSUE THREAD

**Issue by yuzehui1996** [ialhashim/DenseDepth#62]
I use your pretrained model(nyu.h5) to test my own dataset. My dataset might not be the same range as NYU-Depth V2(range 10 meters). My dataset range 0 to 2m. Is it suitable to test my dataset with your pretrained model? If so, how can I change the hyper-parameters(maxDepth and minDepth in utils.predict)?

**Comment by ialhashim** [comment]
Your milage May vary.. Try it out and see how far off are the estimates in the range of 0 to 10.. The model was trained on a range that intersect with what your data is at. The result however depend on many things. The best result would be to fine tune the model if you have ground truth and train the model some more. Changing the liner scaling of the predictions won't magically make the model more accurate.
