### ISSUE TITLE
ValueError: Cannot embed the 'svg' image format

### ISSUE THREAD

**Issue by valentinoPereira** [ialhashim/DenseDepth#63]
Hi, I am using Google colab for development. I wanted to train a densedepth model to check the training accuracy. So I did the following:
1. Cloned the repository
2. Downloaded the NYU dataset mentioned in the readme "nyu_data.zip" and placed it inside the repository.
3. Ran command from readme for training `python train.py --data nyu --gpus 4 --bs 8`

Things start smooth but suddenly I am getting the an error and the training process stops. Following is my output log:
```
Using TensorFlow backend.
Will use 4 GPUs.
Loading base model (DenseNet)..
WARNINGS.... 

Model created.
Output: ./models/1569407560-n6336-e20-bs8-lr0.0001-densedepth_nyu
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    plot_model(model, to_file=runPath+'/model_plot.svg', show_shapes=True, show_layer_names=True)
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/vis_utils.py", line 250, in plot_model
    return display.Image(filename=to_file)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/display.py", line 1015, in __init__
    raise ValueError("Cannot embed the '%s' image format" % (self.format))
ValueError: Cannot embed the 'svg' image format
```

I researched and it seems to be an IPython related issue with no resolution available online. A method needs to be changed in the python libraries as per this link: https://github.com/ipython/ipython/issues/10043

**Comment by Angtrim** [comment]
I think you can just comment out the line 59 of the train.py file

`    plot_model(model, to_file=runPath+'/model_plot.svg', show_shapes=True, show_layer_names=True)
`

You won't have the SVG image of the graph, but the training should proceed correctly.

**Comment by valentinoPereira** [comment]
> I think you can just comment out the line 59 of the train.py file
> 
> ` plot_model(model, to_file=runPath+'/model_plot.svg', show_shapes=True, show_layer_names=True)`
> 
> You won't have the SVG image of the graph, but the training should proceed correctly.

Thanks @Angtrim . This resolves the issue.
