### ISSUE TITLE
loss nan

### ISSUE THREAD

**Issue by cww123456789** [ialhashim/DenseDepth#65]
Hello, I used your code to train my data set, but loss is nan, how should I modify to make loss converge?Personally, I think it's dataloder.Thank you very much!

**Comment by ialhashim** [comment]
Check if your data has any 'zero' values. If so you have a choice of either filling the missing data with some values (grater than zero) or disabling the "DepthNorm" function.

**Comment by cww123456789** [comment]
Hello, according to the method you said, I changed all the lost data to 1. The loss value is always around 15 and does not converge. What should I do?Thank you very much!

**Comment by arijitgupta42** [comment]
> Check if your data has any 'zero' values. If so you have a choice of either filling the missing data with some values (grater than zero) or disabling the "DepthNorm" function.

Hey, how exactly would you recommend to disbale the DepthNorm function? Simply return x instead of maxDepth/x?

**Comment by ialhashim** [comment]
Yes
