### ISSUE TITLE
error when training epoch5

### ISSUE THREAD

**Issue by boni-hu** [ialhashim/DenseDepth#67]
Hi Ibraheem,

when I training epoch5, an error as follows occurred. Thank you for your help.

![errors](https://user-images.githubusercontent.com/37893834/65925445-46df9180-e434-11e9-866b-66842985f4c3.png)

Best regards,
Boni

**Comment by bat3a** [comment]
hi
did you solve the error you mentioned? i have it too, and tried to modify network.py as suggested on other issues, but didn't work!
