### ISSUE TITLE
Convert output to correct depth map

### ISSUE THREAD

**Issue by Zhu-Jinkuan** [ialhashim/DenseDepth#69]
Hi, 
   Thanks for your impressive work first! I used the Kitti.h5 pretrained model to validate the pictures from KITTI datasets.  I use your code in test.py. Should I change the parameters Mindepth and Maxdepth because  I found the default value is 10 and 1000(by the way, does 1000 mean 1000m or 1000cm?), which is set for NYU datasets.  And what function should I use to convert the output to depth map?

**Comment by ialhashim** [comment]
Yes, 1000 is CM (meaning the maximum is 10 meters). For KITTI it was trained on min of 1 meters and maximum of 80 meters. So the values should be `minDepth = 1.0` and `maxDepth = 80.0`

**Comment by Zhu-Jinkuan** [comment]
> Yes, 1000 is CM (meaning the maximum is 10 meters). For KITTI it was trained on min of 1 meters and maximum of 80 meters. So the values should be `minDepth = 1.0` and `maxDepth = 80.0`

Thanks for your reply! So after I get the outputs, is it correct to use this function:
  depth = 80 * outputs   
to get the real depth ?

**Comment by ialhashim** [comment]
Yes, if you call the function with the correct range https://github.com/ialhashim/DenseDepth/blob/master/utils.py#L7

**Comment by Zhu-Jinkuan** [comment]
> Yes, if you call the function with the correct range https://github.com/ialhashim/DenseDepth/blob/master/utils.py#L7

I still wonder why you use DepthNorm here? are predictions the real depth map? Can I just use the predictions to represent the depth instead of doing the DepthNorm? 
![image](https://user-images.githubusercontent.com/42997811/66712407-bfe4ce80-edce-11e9-9010-c02954ff8c49.png)

**Comment by ialhashim** [comment]
The predictions are in `maxDepth / depth` range. We take this inverse to penalize errors on near by objects which are more accurately captured by the depth sensor.

**Comment by jdanielhoyos** [comment]
@ialhashim Hello. I didnt get it. The code utils says "def predict(model, images, minDepth=10, maxDepth=1000, batch_size=2):"
On the other hand I'm using the kitti.h5 pre trained network. For a given custom image I got values between  0.5363473 and 0.056947958,  (is a city block view) to what number do I have to multiply these outputs to get the real depth estimation in meters? Thanks.
