### ISSUE TITLE
Regarding normalizing data in TF2.0

### ISSUE THREAD

**Issue by sadique-adnan** [ialhashim/DenseDepth#71]
In data.py file written in TF2.0
Why there was need to divide the depth value by 255.0 when tf.image.convert_image_dtype is already been used to normalize the depth values between [0,1]

![Screenshot from 2019-10-18 01-00-12](https://user-images.githubusercontent.com/6484088/67053772-a9c66d80-f142-11e9-82d8-379ae33c0c28.png)

**Comment by ialhashim** [comment]
The TF2.0 version is just an experiment, if you can confirm that this is wrong I would be happy to accept a pull request.
