### ISSUE TITLE
Using different dataset

### ISSUE THREAD

**Issue by ugamman** [ialhashim/DenseDepth#72]
Hi,
thanks for your work. I'm trying to use this network to train it with my dataset (i generated it with Carla simulator). But I have some problems with setting parameters, I think.
The max depth of the images is 1km but the meaningful information stop to 70 meters (this is my Max depth). Where should I change the values of the max Depth? 
This is an image of my dataset:
![000004](https://user-images.githubusercontent.com/55691872/67163423-f0001480-f36e-11e9-9b8a-64d63db16416.png)

**Comment by ialhashim** [comment]
The input to the network should match the output you expect. If you input depth images in the range of (0.1 to 70) the network will output that (provided you don't use the DepthNorm function). If you plan to train on maxDepth / depth then make sure all the numbers are correct.

**Comment by ugamman** [comment]
Thanks for the answer, so if I understood correctly:
1. if I want to have values between 0 and 70 as output image I don't have to use the NormDepth function anywhere (I delete it), am I right?
2. in which range should I pass the depth image? [0, 1] or [0, 255] or [0, 70]?
3. regarding the loss function, how can the maxDepthVal value be set?
4. if I wanted to use the DepthNorm function, in which range should I feed the depth image to the network?
Thank you in advance!
