### ISSUE TITLE
Computing depth from depth map

### ISSUE THREAD

**Issue by shazal** [ialhashim/DenseDepth#73]
Hey is it possible to calculate exact depth in m/cm from depth map? If you can guide me in this regards that would be really helpful. Thankyou.

Best,
Shaza;

**Comment by ialhashim** [comment]
Keep in mind these CNN models do not produce depths with high accuracy for real world data. The predict function returns the depths in the range (0 to 1) so you just need to multiply by the maximum depth found in the training set (10 meters or 1000CM).
