### ISSUE TITLE
About predict() and predictions

### ISSUE THREAD

**Issue by boni-hu** [ialhashim/DenseDepth#74]
Hello ialhashim,

Thank for your great project and kind help before. I have a new question about the predict() as follows:
![predict](https://user-images.githubusercontent.com/37893834/67260291-55c2dc80-f4e6-11e9-8738-a2e98a980ca0.png)
 The 'predictions' is the output of the model, so the loss function is to compute the loss between 'predictions' and 'y_true' ? And the return value 'np.clip(DepthNorm(predictions, maxDepth=1000), minDepth, maxDepth) / maxDepth' is the output of test, not the value to compute loss? Is it right?
Thank you again!

Boni

**Comment by ialhashim** [comment]
The loss is computed in the 'maxDepth / depth' range not from 0 to 1.

**Comment by boni-hu** [comment]
Thank you very much!
