### ISSUE TITLE
Mismatch with paper results

### ISSUE THREAD

**Issue by dulucas** [ialhashim/DenseDepth#75]
Hello, thanks for sharing your code, I downloaded the pre-trained weights and tested on the NYU test dataset that you released, but I got different results comparing your results in your paper. 
The results using pretrained weights are :
a1,          a2,         a3,        rel,        rms,       log_10
0.8471  0.9731  0.9937, 0.1274  0.5485   0.0535
where the results of paper are:
a1,         a2,         a3,        rel,        rms,     log_10
0.846   0.974    0.994   0.123     0.465    0.053
Backend:
tensorflow 1.14
CUDA 10.1
keras 2.2.4

Bests

**Comment by dulucas** [comment]
with keras 2.3.1 tensorflow 1.13.1, the pre-trained network produce the same results

**Comment by dulucas** [comment]
@ialhashim

**Comment by ialhashim** [comment]
If you plan to compare against these results please use the new results. The old results in the paper used a different code base and training schedule that is not as easy to replicate as this repo. Also, if you swap up the encoder with a more recent one you would get much better results (state of the art), we are working on this for our next report.
