### ISSUE TITLE
Regarding utils.predict method

### ISSUE THREAD

**Issue by sadique-adnan** [ialhashim/DenseDepth#77]
![Screenshot from 2019-11-08 19-25-29](https://user-images.githubusercontent.com/6484088/68501027-6badfc80-025d-11ea-8ce6-f76e77c90d16.png)
Thanks for the amazing work Ibraheem.

I wanted to ask whether the prediction from model before applying DepthNorm is Depth map or Disparity Map? 
The visualization of the output shown in the paper is different while reproducing it on Kitti using 'plasma' colormaps on the predicted output.
And after applying Depth Norm do we need to divide it by max depth or multiply it by max depth to get the real depth in meters.
![Screenshot from 2019-11-08 19-14-03](https://user-images.githubusercontent.com/6484088/68500559-453b9180-025c-11ea-990b-264eec632c6c.png)

**Comment by ialhashim** [comment]
Its a depth map. To get back the prediction in meters you multiply by maximum depth in the training set (80 for KITTI).
