### ISSUE TITLE
the version of tensorflow and keras

### ISSUE THREAD

**Issue by shuluoshu** [ialhashim/DenseDepth#78]
Hi , @ialhashim 
 I am using Keras:  (2.2.4)  with tensorflow backend (1.4.1) , when I try to train the model, it runs into error: 

> 'tensorflow.python.ops.image_ops' has no attribute 'image_gradients'

So i want to know what's your version of tf and keras ? Thanks a lot!

**Comment by ialhashim** [comment]
A TensorFlow version around 1.13 should work.

**Comment by shuluoshu** [comment]
> A TensorFlow version around 1.13 should work.

Sorry, what if I don't have cuda10, does lower version support this operation ? The error is as follows:

**Comment by ialhashim** [comment]
This error indicates that function is missing. Try to investigate which TensorFlow function introduced it and try to work from that. Othereise reimplement it or just drop this error term all togther if you just want to test some things.

**Comment by pearsonkyle** [comment]
Bump. I too am having difficulty with versions but get a different error. Could you please supply version numbers from a pip freeze? 

The newest version of keras (2.3.1) and tensorflow (2.0.0) will not work
