### ISSUE TITLE
Regarding Loss Function

### ISSUE THREAD

**Issue by sadique-adnan** [ialhashim/DenseDepth#79]
Hi Ibraheem, Thanks for the clarifying the doubts before.

I am not able to understand the need to take mean for l_depth and l_edges twice for calculating overall loss function. The mean has already been evaluated channel wise then is it necessary to take the mean again.
Thanks in advance.
![Screenshot from 2019-11-11 13-30-07](https://user-images.githubusercontent.com/6484088/68589585-8ca86480-048c-11ea-8d3d-fc3ae13efe56.png)

**Comment by ialhashim** [comment]
It might have been an artifact of previous loss functions. If you have a more elegent way to
