### ISSUE TITLE
Hi! I want to get one picture's depth and save it, I don't want to get the depth which is displayed. How should I do? Thank you!

### ISSUE THREAD

**Issue by lijialei666** [ialhashim/DenseDepth#8]

**Comment by ialhashim** [comment]
You can modify the `test.py` code and save a single colormapped output by doing the following:
```
import numpy as np
import matplotlib.pyplot as plt

colorMapped = plt.get_cmap('plasma')(outputs[0,:,:,0])[:,:,:3]

Image.fromarray(np.clip(colorMapped*255, 0, 255).astype('uint8')).save('output.png')
```
If you want to save a binary representation you can use:
```
import numpy as np
np.save('output.npy', outputs[0,:,:,0])
```

Does that answer the question?

**Comment by lijialei666** [comment]
en..., I want to get a gray picture, but not the color picture. How should I do. Thank you.

**Comment by ialhashim** [comment]
`outputs[0,:,:,0]` is simply a gray scale depth map. You could also change `'plasma'` with any colormap you like (including `'grey'`).

**Comment by lijialei666** [comment]
Ok! You are very nice and friendly. I will try it. Thank you very much!

**Comment by ialhashim** [comment]
You are welcome.

**Comment by lijialei666** [comment]
Hi! I meet another problem. I want to get a lot of depths for RGB picture. But If I put a lot of pictures to the examples, my CPU will  Overloading. What should I do? Thank you very much.

**Comment by lijialei666** [comment]
And it's so slowly.

**Comment by ialhashim** [comment]
Are you using a GPU? you should be able to compute around 4 to 6 images in less than a second at a time. Only loading the model and the first prediction are usually slow (due to Keras...).

**Comment by lijialei666** [comment]
en... I want to run more than 100000 pictures, how should I do? I put all the pitctures to examples or load the pictures by .csv. How should I do? Thank you all the same.

**Comment by chris-aeviator** [comment]
how to save the pointcloud to be used e.g. in potree?

**Comment by chris-aeviator** [comment]
I believe the pointcloud is never available as a whole in demo.py but rather calculated from the current perspective. I ended up exporting the colormaps with colorscheme `gray` and use open3d (http://www.open3d.org/docs/release/tutorial/geometry/rgbd_image.html?highlight=jpg#TUM-dataset) to create a pointcloud from DenseDepth's densemap prediction and the original image. Open3d let's you then save the Pointcloud to e.g. .ply

**Comment by laisimiao** [comment]
> You can modify the `test.py` code and save a single colormapped output by doing the following:
> 
> ```
> import numpy as np
> import matplotlib.pyplot as plt
> 
> colorMapped = plt.get_cmap('plasma')(outputs[0,:,:,0])[:,:,:3]
> 
> Image.fromarray(np.clip(colorMapped*255, 0, 255).astype('uint8')).save('output.png')
> ```
> 
> If you want to save a binary representation you can use:
> 
> ```
> import numpy as np
> np.save('output.npy', outputs[0,:,:,0])
> ```
> 
> Does that answer the question?


So here outputs is output of keras or output of pytorch? Because their outputs are different and I am not familiar with tf/keras.
