### ISSUE TITLE
Random crop or resize for input training data

### ISSUE THREAD

**Issue by shuluoshu** [ialhashim/DenseDepth#80]
Hi @ialhashim ,
I notice that you use 384x 1284 for KITTI training, now I have a dataset that has over 3700x 2640 size, I find you use **resize** in data preparation,  however, in my case, the resize operation loses the details of the input large img. I wonder if I can use **Crop** every time (randomly crop out 480x640 image patches ) during minibatch training. Does it affect the training? 
Thanks!

**Comment by ialhashim** [comment]
Keep in mind all depth estimations happen now at half the input resolution. This is mainly a hardware decided limitation. If you have a card like the Quadro RTX with 48 GB you might be able to go full resolution. But for now I would advice training such that you get at least batch size of 8 while training. If you crop the method will learn to estimate depth on crops. I am not sure if this is more useful in practice as opposed to upsampling the depth, especially that these CNN based depth estimation methods are not that accurate.
