### ISSUE TITLE
About backbone

### ISSUE THREAD

**Issue by animareversed** [ialhashim/DenseDepth#81]
Hi,
Thanks for your work. I was wondering if it's possible put a Resnet as backbone instead of Densenet. 
What about skip connections between encoder and decoder? It would be possible do those connections with a Resnet too?
Thanks,
Best regards

**Comment by ialhashim** [comment]
Yes of course. The architecture is pretty straightforward you can replace the encoder with whatever network. For the very useful skip connections, you can try to find intermediate exit points that match the shape of the up-sampled layer and simply connect it there. The best depth network we have found using our method is EfficentNet B7. It produces state of the art.
