### ISSUE TITLE
Cannot automatic save model after each epoch

### ISSUE THREAD

**Issue by shuluoshu** [ialhashim/DenseDepth#82]
Hi， @ialhashim 
I am not familiar with Keras. The training process seems no problem, however, after one epoch is finished, there is no automatic model saving. Now I have trained to the 4th epoch, and cannot see any saved model. Do I have to wait for all 60 epochs finish?  

```
model.fit_generator(train_generator, callbacks=callbacks, validation_data=test_generator, epochs=args.epochs, shuffle=True)# Start training
basemodel.save(runPath + '/model_apollo.h5')# Save the final trained model: 
```

thanks.

**Comment by ialhashim** [comment]
Look into this callback https://github.com/ialhashim/DenseDepth/blob/635ad80cd0665fc213c07c547730a84bbfcb4ffc/callbacks.py#L83

You can modify it to save at each epoch. Also to test this you can modify the data.py file to only train on partial set.
