### ISSUE TITLE
Pytorch loss version

### ISSUE THREAD

**Issue by animareversed** [ialhashim/DenseDepth#83]
Hi (again :) ),
I saw that in the pytorch version there is not the edges loss (the second loss term Lgrad ), why? Is it not possible to implement it?
Thanks,
Best regards

**Comment by ialhashim** [comment]
As stated the PyTorch implementation is only experimental, I wrote in a day and didn't get a chance to modify it. I leave this task to the community, I would be happy to do a pull request.

**Comment by animareversed** [comment]
Ok, thanks.
But, last question ( I hope): when you do this:
l_edges = K.mean(K.abs(dy_pred - dy_true) + K.abs(dx_pred - dx_true), axis=-1)

you set axis equal to -1 because you have [batch_size, height, width, depth], right? So you do the mean with respect to the depth dimension.
Thanks in advance

**Comment by ialhashim** [comment]
Yes

**Comment by animareversed** [comment]
Thnak you, so much
