### ISSUE TITLE
Inference on other dataset, about the intrinsics.

### ISSUE THREAD

**Issue by shuluoshu** [ialhashim/DenseDepth#85]
Hi, @ialhashim 
It's me again, sorry for bothering you.
I wonder if I have a dataset with original focal lenth F1 and Image size: `W x H,` as well as the max depth: 100 meters.  First I resize the images to `W/2 x H/2` and send them into training. During test, I have another image with focal Length F2 and image size `4W x 4H`, I also resize them into  `W/2 x H/2` as training  preprocess does. The predicted output  is `dpred`. So I have two questions: 

1.  for training phase, the resized image have a pesudo-focal length of `F1/2` if the max depth is still regarded as 100m , am I right? 
2. for testing on another image, the real depth should be:  `0.5F1  /  0.125F2  == dreal / dpred`， so `dreal = 100 * dpred * (0.5F1  /  0.125F2) `, do I understand it right ? 

Thanks so much !

**Comment by ialhashim** [comment]
This is a bit outside my expertise, I am not sure I can help with this at this time. Sorry about that.
