### ISSUE TITLE
KITTI Data Prep.

### ISSUE THREAD

**Issue by tomer5656** [ialhashim/DenseDepth#86]
Hi,
Can you please elaborate about the KITTI dataset prep?
I assume that you need to project the LIDAR points to the RGB image and interpolate between them and then crop the part without the information.
It will be great to get the preparation scheme of the KITTI dataset.

Thanks,
Tomer

**Comment by zozobozo** [comment]
Hi Tomer,
KITTI already provides a dataset where the lidar is projected unto the image; furthermore - you have as "ground-truth" accumulated lidar points from several frames around a given frame, cleaned by SGM stereo. You can take a look [in the "depth-completion" benchmark](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion).

Best,
Z.

**Comment by zozobozo** [comment]
Hi Ibrahim,

It would be great however if you could please include your kitti data loaders.

Best,
Z.
