### ISSUE TITLE
Clipping KITTI dataset

### ISSUE THREAD

**Issue by tomer5656** [ialhashim/DenseDepth#88]
Hi,
how do you determine the clipping of the kitti dataset depth map? 
Thanks,
Tomer

**Comment by ialhashim** [comment]
This code can help https://github.com/nianticlabs/monodepth2/blob/bd03a9ec1305082e80199bc2753ef5adb252e405/evaluate_depth.py

**Comment by tomer5656** [comment]
Thanks a lot!

**Comment by tomer5656** [comment]
So you just clip it between 1e-3 to 80?
