### ISSUE TITLE
Frozen layers encoder

### ISSUE THREAD

**Issue by animareversed** [ialhashim/DenseDepth#89]
Hi,
If I understood well reading the paper, the encoder layers should be frozen, instead in the code it seems that they are not. Should I set False here:

`for layer in base_model.layers: layer.trainable = True`

and do the same in the pytorch code.
Thanks in advance

**Comment by ialhashim** [comment]
No freezing was used. This line of code is just there for debugging. You can ignore it.

**Comment by animareversed** [comment]
Thank you. So in pytorch should I add:

```
for param in model.parameters():
    param.requires_grad = False
```

**Comment by ialhashim** [comment]
I don't think so, like I said NO freezing is used for our method.

**Comment by animareversed** [comment]
Sorry i thoguht it was "no, freezing was used". Ok, thank you :)
