### ISSUE TITLE
depth prediction

### ISSUE THREAD

**Issue by boni-hu** [ialhashim/DenseDepth#9]
Hi,
Thanks for your great contribution, I have great interest. Now i have two question as follows.
Firstly, about the network architecture, why not continue to upsample  to get the depth map of 640X480 resolution as the same as the input images?
Next, why you define the target depth map y as y=m/y(orig).
Thank you for your reply.

**Comment by ialhashim** [comment]
Q 1) We experimented with adding an up-sampling layer at the end but it didn't seem to help. Furthermore, two issues arise from such a modification: (a) GPU memory consumption increases (b) no good matching layers in the decoder have the same spatial dimension.

Q 2) This is a quick attempt at both down playing the artificial exaggeration of the losses at larger depths and focus the learning on regions of higher accuracy. This and similar ideas are used in many other works.
