### ISSUE TITLE
Adding NYU Dataset to TensorFlow Datasets

### ISSUE THREAD

**Issue by lgeiger** [ialhashim/DenseDepth#90]
Thanks for publishing the repo and the dataset with the dense labels.
A while ago I wrapped the dataset which can be downloaded from https://s3-eu-west-1.amazonaws.com/densedepth/nyu_data.zip into the format for [TensorFlow Datasets](https://www.tensorflow.org/datasets/) (see [here](https://github.com/lgeiger/datasets/blob/nyu-depth/tensorflow_datasets/image/nyu_depth_v2.py)). Though I never made a PR to TensorFlow Datasets since it would need to download the data from that URL: https://github.com/tensorflow/datasets/issues/838#issuecomment-561558166

Are there any license restrictions to use the data from https://s3-eu-west-1.amazonaws.com/densedepth/nyu_data.zip, would you be OK with me adding it to TensorFlow Datasets?

**Comment by ialhashim** [comment]
Yes, please do so! and I would be happy to apply the PR.

Although this particular set is not something special. I've been using it because I found it online. A better dataset would be the full NYU v2 with dense depth maps and people can then pull out any subset they need.

**Comment by lgeiger** [comment]
Thanks, I will make a PR to TensorFlow Datasets.

> A better dataset would be the full NYU v2 with dense depth maps and people can then pull out any subset they need.

I agree. Though that would need a bit more work 😉

**Comment by lgeiger** [comment]
Made the PR: https://github.com/tensorflow/datasets/pull/1259

**Comment by ialhashim** [comment]
Will the dataset be hosted at Google's servers? otherwise this will incur unforeseen costs on me!

**Comment by lgeiger** [comment]
> Will the dataset be hosted at Google's servers.

No, it will be downloaded once by every user trying to use the dataset and will be converted to TFRecords and then stored locally so subsequent uses won't need network requests.

> otherwise this will incur unforeseen costs on me!

What about uploading the dataset to a GitHub release? That way it will still be able to automatically download and doesn't add extra cost for you.

**Comment by ialhashim** [comment]
Can we do it with  GitHub release? I am not sure how big of files they support. I am okay with hosting it anywhere else. The current server I had to pay for it, so that is why I removed the old link and now link to a Google drive.

**Comment by lgeiger** [comment]
> Can we do it with GitHub release? I am not sure how big of files they support.

Not sure, but worth a try.

> The current server I had to pay for it, so that is why I removed the old link and now link to a Google drive.

Makes sense. The only problem with google drive is that it cannot be downloaded automatically via python
