### ISSUE TITLE
The train resolution and the test resolution

### ISSUE THREAD

**Issue by boni-hu** [ialhashim/DenseDepth#93]
Hi Ialhashim,

Thank you for your great work. I have already trained a model with my dataset which have 640x480 resolution images. The resolution is the same as your dataset and network input. And then i test with 480x480 image. Have any influence on depth estimation if the train and test data have different resolution?  Do I need to train with 480x480 and change the network?

Best regards,
Boni

**Comment by ialhashim** [comment]
There might be some influence. From my experiments if the aspect ratio is changed or other lens parameters are changed (e.g. different camera) the performance can be lower. I think the best thing to do is try both and see how it goes.

**Comment by boni-hu** [comment]
Thank you very much!
