### ISSUE TITLE
any link NYU Depth V2?

### ISSUE THREAD

**Issue by kimtaehyeong** [ialhashim/DenseDepth#94]
any link NYU Depth V2?

https://tinyurl.com/nyu-data-zip

I can't download this size because I can't access it. Do you have any other links?
Thank you.

**Comment by ialhashim** [comment]
Does this work

https://drive.google.com/file/d/1fdFu5NGXe4rTLYKD5wOqk9dl-eJOefXo/view?usp=drivesdk

**Comment by kimtaehyeong** [comment]
Thank you.
