### ISSUE TITLE
tensorflow  version is not compatible with cuda version

### ISSUE THREAD

**Issue by LiZhenLiangLee** [ialhashim/DenseDepth#95]
Hi, thanks for your work.
You said that you test your code with tensorflow 1.13 and cuda 9.0. My system's cuda version is 9.0, but after I install  tensorflow 1.13.1, and run test.py, I got following error:

> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test.py", line 8, in <module>
>     from keras.models import load_model
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
>     from . import utils
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
>     from . import conv_utils
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
>     from .. import backend as K
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
>     from .tensorflow_ckend import *
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
>     import tensorflow as tf
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "/data/lizhenliang/anaconda3/envs/HQM/lib/python3.6/imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

And I search the error  'ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory' ,  most of the answer said that tensorflow 1.13 only support cuda10. So how can you run the code with tensorflow 1.13 and cuda 9.0?

**Comment by ialhashim** [comment]
I might have made a mistake on the cuda version. Try running with cuda 10 or whatever your tensorflow need that should fix it.
